"use client";

/* eslint-disable @next/next/no-img-element -- gallery URLs use the deployment-configured media origin, not a fixed build-time host allowlist. */

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ApiError } from "@/src/services/api";
import { authService } from "@/src/services/auth.service";
import { partnerService } from "@/src/services/partner.service";
import { tokenStorage } from "@/src/services/token-storage";
import type { AmenityData, PartnerHotelProfile, PropertyType } from "@/src/types/partner";

const types: PropertyType[] = ["HOTEL", "RESORT", "VILLA", "APARTMENT", "HOSTEL", "HOMESTAY"];
const pretty = (v: string | null) => v ? v.replaceAll("_", " ").toLowerCase().replace(/\b\w/g, c => c.toUpperCase()) : "Not submitted";
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="field-label">{label}</span>{children}</label>; }
function Badge({ title, value, good }: { title: string; value: string; good?: boolean }) { return <div className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs font-black uppercase tracking-wider text-slate-400">{title}</p><p className={`mt-2 inline-flex rounded-full px-2.5 py-1 text-xs font-black ${good ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-800"}`}>{value}</p></div>; }

export default function HotelProfilePage() {
  const router = useRouter(); const [profile, setProfile] = useState<PartnerHotelProfile | null>(null); const [facilities, setFacilities] = useState<AmenityData[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [imageFile, setImageFile] = useState<File | null>(null); const [imageAlt, setImageAlt] = useState("");
  const load = useCallback(async () => { setError(""); try { const user = await authService.getCurrentUser(); if (!user || user.role !== "HOTEL_PARTNER") { router.replace("/partner/login"); return; } const [next, options] = await Promise.all([partnerService.getProfile(), partnerService.getFacilities()]); setProfile(next); setFacilities(options); } catch (e) { if (e instanceof ApiError && e.status === 404) router.replace("/partner/onboarding"); else setError("We could not load your hotel profile. Please try again."); } finally { setLoading(false); } }, [router]);
  useEffect(() => { if (!tokenStorage.getTokens()) router.replace("/partner/login"); else queueMicrotask(() => void load()); }, [load, router]);
  async function save(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if (!profile) return; const data = new FormData(e.currentTarget); const get = (k: string) => String(data.get(k) ?? "").trim(); if (!get("name") || !get("address_line1") || !get("city") || !get("postal_code")) { setError("Complete the required property and location fields."); return; } setSaving(true); setError(""); try { setProfile(await partnerService.updateProfile({ name: get("name"), description: get("description") || undefined, property_type: get("property_type") as PropertyType, address_line1: get("address_line1"), address_line2: get("address_line2") || undefined, city: get("city"), district: get("district") || undefined, state: "Maharashtra", postal_code: get("postal_code"), contact_email: get("contact_email") || undefined, contact_phone: get("contact_phone") || undefined, check_in_time: get("check_in_time"), check_out_time: get("check_out_time") })); setNotice("Profile details saved."); } catch (x) { setError(x instanceof Error ? x.message : "Unable to save the profile."); } finally { setSaving(false); } }
  async function saveFacilities() { if (!profile) return; setSaving(true); try { setProfile(await partnerService.updateFacilities(profile.amenities.map(a => a.id))); setNotice("Facilities updated."); } catch (x) { setError(x instanceof Error ? x.message : "Unable to update facilities."); } finally { setSaving(false); } }
  async function addImage(e: FormEvent) { e.preventDefault(); if (!imageFile) { setError("Choose a JPEG, PNG, or WebP photo."); return; } if (!["image/jpeg", "image/png", "image/webp"].includes(imageFile.type) || imageFile.size > 8 * 1024 * 1024) { setError("Choose a JPEG, PNG, or WebP image that is 8 MB or smaller."); return; } setSaving(true); setError(""); try { await partnerService.uploadProfileImage(imageFile, imageAlt || undefined); setImageFile(null); setImageAlt(""); setNotice("Photo uploaded."); await load(); } catch (x) { setError(x instanceof Error ? x.message : "Unable to upload photo."); } finally { setSaving(false); } }
  async function removeImage(id: number) { setSaving(true); try { await partnerService.deleteProfileImage(id); setNotice("Photo removed."); await load(); } catch (x) { setError(x instanceof Error ? x.message : "Unable to remove photo."); } finally { setSaving(false); } }
  async function setPrimary(id: number) { setSaving(true); try { await partnerService.setProfilePrimaryImage(id); setNotice("Primary photo updated."); await load(); } catch (x) { setError(x instanceof Error ? x.message : "Unable to update the primary photo."); } finally { setSaving(false); } }
  async function moveImage(id: number, direction: -1 | 1) { if (!profile) return; const images = [...profile.images].sort((a, b) => a.display_order - b.display_order); const index = images.findIndex(image => image.id === id); const next = index + direction; if (index < 0 || next < 0 || next >= images.length) return; [images[index], images[next]] = [images[next], images[index]]; setSaving(true); try { await partnerService.reorderProfileImages(images.map(image => image.id)); setProfile({ ...profile, images: images.map((image, order) => ({ ...image, display_order: order })) }); setNotice("Photo order saved."); } catch (x) { setError(x instanceof Error ? x.message : "Unable to reorder photos."); } finally { setSaving(false); } }
  if (loading) return <main className="min-h-screen bg-slate-50 p-6"><div className="mx-auto max-w-6xl space-y-5"><div className="skeleton h-10 w-64 rounded-xl" /><div className="skeleton h-96 rounded-2xl" /></div></main>;
  if (!profile) return <main className="min-h-screen bg-slate-50 p-6"><div className="mx-auto max-w-xl rounded-2xl bg-white p-8 text-center shadow-sm">Profile unavailable. <button className="primary-button ml-3" onClick={() => void load()}>Retry</button></div></main>;
  const selected = new Set(profile.amenities.map(a => a.id));
  return <main className="min-h-screen bg-[#f0f4f8] py-6 sm:py-10"><div className="mx-auto max-w-6xl px-4 sm:px-6"><div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2"><Link href="/partner/dashboard" className="text-sm font-bold text-slate-500 hover:text-slate-900">← Dashboard</Link><span className="text-slate-300">·</span><Link href="/partner/room-types" className="text-sm font-bold text-[#172554] hover:underline">Room Types →</Link></div><h1 className="mt-2 text-3xl font-black tracking-tight text-[#0b163d]">Hotel profile</h1><p className="mt-1 text-sm text-slate-500">Keep your property information accurate for verification and launch.</p></div><div className="rounded-xl bg-white px-4 py-3 shadow-sm"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Profile completion</p><p className="text-2xl font-black text-[#172554]">{profile.profile_completion_percent}%</p></div></div><section className="mb-6 grid gap-3 sm:grid-cols-3"><Badge title="Profile" value={profile.is_profile_complete ? "Complete" : `${profile.profile_completion_percent}% complete`} good={profile.is_profile_complete} /><Badge title="Verification" value={pretty(profile.verification_status)} good={profile.verification_status === "APPROVED"} /><Badge title="Booking gateway" value={pretty(profile.booking_gateway_status)} good={profile.booking_gateway_status === "ACTIVE"} /></section>{error && <div role="alert" className="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>}{notice && <div className="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{notice}</div>}
    <form onSubmit={save} className="space-y-6"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 className="text-lg font-black text-[#0b163d]">Property details</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Hotel name *"><input name="name" defaultValue={profile.name} required className="field-input" /></Field><Field label="Property type *"><select name="property_type" defaultValue={profile.property_type} className="field-input">{types.map(t => <option key={t}>{t}</option>)}</select></Field><div className="sm:col-span-2"><Field label="Description"><textarea name="description" defaultValue={profile.description ?? ""} rows={4} maxLength={10000} className="field-input" /></Field></div></div></section><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 className="text-lg font-black text-[#0b163d]">Location and contact</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Street address *"><input name="address_line1" defaultValue={profile.address_line1} required className="field-input" /></Field><Field label="Address line 2"><input name="address_line2" defaultValue={profile.address_line2 ?? ""} className="field-input" /></Field><Field label="City *"><input name="city" defaultValue={profile.city} required className="field-input" /></Field><Field label="District"><input name="district" defaultValue={profile.district ?? ""} className="field-input" /></Field><Field label="State"><input value="Maharashtra" disabled className="field-input bg-slate-50" /></Field><Field label="Pincode *"><input name="postal_code" defaultValue={profile.postal_code} required className="field-input" /></Field><Field label="Contact email"><input name="contact_email" type="email" defaultValue={profile.contact_email ?? ""} className="field-input" /></Field><Field label="Phone (E.164)"><input name="contact_phone" placeholder="+919876543210" defaultValue={profile.contact_phone ?? ""} className="field-input" /></Field><Field label="Check-in time"><input name="check_in_time" type="time" defaultValue={profile.check_in_time.slice(0, 5)} className="field-input" /></Field><Field label="Check-out time"><input name="check_out_time" type="time" defaultValue={profile.check_out_time.slice(0, 5)} className="field-input" /></Field></div><button disabled={saving} className="primary-button mt-6">{saving ? "Saving…" : "Save profile"}</button></section></form>
    <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-wrap items-baseline justify-between gap-2"><div><h2 className="text-lg font-black text-[#0b163d]">Basic facilities</h2><p className="mt-1 text-sm text-slate-500">Select facilities guests can expect at the property.</p></div><button disabled={saving} onClick={() => void saveFacilities()} className="secondary-button">Save facilities</button></div><div className="mt-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{facilities.length ? facilities.map(item => <label key={item.id} className="flex cursor-pointer items-center gap-3 rounded-xl border border-slate-200 p-3 text-sm font-bold text-slate-700"><input type="checkbox" checked={selected.has(item.id)} onChange={() => setProfile(current => current ? { ...current, amenities: selected.has(item.id) ? current.amenities.filter(a => a.id !== item.id) : [...current.amenities, item] } : current)} />{item.name}</label>) : <p className="text-sm text-slate-500">No facilities are configured yet.</p>}</div></section>
    <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7"><h2 className="text-lg font-black text-[#0b163d]">Property gallery</h2><p className="mt-1 text-sm text-slate-500">Upload JPEG, PNG, or WebP images up to 8 MB. The first photo becomes primary automatically.</p><form onSubmit={addImage} className="mt-5 grid gap-3 md:grid-cols-[1fr_220px_auto]"><input required type="file" accept="image/jpeg,image/png,image/webp" onChange={e => setImageFile(e.target.files?.[0] ?? null)} className="field-input py-2" /><input value={imageAlt} onChange={e => setImageAlt(e.target.value)} maxLength={255} placeholder="Photo description" className="field-input" /><button disabled={saving} className="primary-button">{saving ? "Uploading…" : "Upload photo"}</button></form><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{profile.images.length ? [...profile.images].sort((a, b) => a.display_order - b.display_order).map((image, index) => <article key={image.id} className="overflow-hidden rounded-xl border border-slate-200 bg-white"><img src={image.image_url} alt={image.alt_text ?? profile.name} className="h-40 w-full object-cover" /><div className="space-y-2 p-3"><div className="flex items-center justify-between gap-2"><span className="truncate text-xs font-bold text-slate-600">{image.is_cover ? "Primary photo" : image.alt_text || "Property photo"}</span>{image.is_cover && <span className="rounded-full bg-emerald-50 px-2 py-0.5 text-[10px] font-black text-emerald-700">PRIMARY</span>}</div><div className="flex flex-wrap gap-2"><button type="button" disabled={saving || image.is_cover} onClick={() => void setPrimary(image.id)} className="text-xs font-black text-[#172554] disabled:text-slate-300">Set primary</button><button type="button" disabled={saving || index === 0} onClick={() => void moveImage(image.id, -1)} className="text-xs font-black text-slate-600 disabled:text-slate-300">Move up</button><button type="button" disabled={saving || index === profile.images.length - 1} onClick={() => void moveImage(image.id, 1)} className="text-xs font-black text-slate-600 disabled:text-slate-300">Move down</button><button type="button" disabled={saving} onClick={() => void removeImage(image.id)} className="text-xs font-black text-red-600">Remove</button></div></div></article>) : <div className="rounded-xl border border-dashed border-slate-300 p-6 text-sm text-slate-500">No property photos yet. Upload your first image to create the gallery.</div>}</div></section>
  </div></main>;
}
