"use client";

import { FormEvent, useEffect, useState } from "react";
import Image from "next/image";
import { advertisingService } from "@/src/services/advertising.service";
import type { AdvertisingConfig, Campaign } from "@/src/types/advertising";
import { openPaymentCheckout } from "@/src/lib/payment-checkout";

export default function AdvertisingPage() {
  const [config, setConfig] = useState<AdvertisingConfig>(); const [items, setItems] = useState<Campaign[]>([]);
  const [plan, setPlan] = useState(""); const [start, setStart] = useState(""); const [district, setDistrict] = useState(""); const [destination, setDestination] = useState("");
  const [file, setFile] = useState<File>(); const [alt, setAlt] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const load = async () => { const [nextConfig, campaigns] = await Promise.all([advertisingService.config(), advertisingService.list()]); setConfig(nextConfig); setItems(campaigns); setPlan((current) => current || nextConfig.plans[0]?.code || ""); };
  useEffect(() => { queueMicrotask(() => { void load().catch((e: unknown) => setMessage(e instanceof Error ? e.message : "Could not load campaigns.")); }); }, []);
  const selected = config?.plans.find((item) => item.code === plan);
  async function create(event: FormEvent) { event.preventDefault(); if (!file) return setMessage("Choose a campaign image."); setBusy(true); setMessage(""); try { const campaign = await advertisingService.create({ plan_code: plan, start_at: new Date(start).toISOString(), district_slug: district || undefined, destination_slug: destination || undefined, alt_text: alt || undefined }); await advertisingService.upload(campaign.id, file, alt); const order = await advertisingService.pay(campaign.id); if (order.provider === "RAZORPAY") await openPaymentCheckout(order, `Advertising campaign ${campaign.id}`); setMessage("Payment evidence is being verified. Campaign approval remains a separate Admin review."); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "Campaign could not be created."); } finally { setBusy(false); } }
  async function pay(id: number) { setBusy(true); setMessage(""); try { const order = await advertisingService.pay(id); if (order.provider === "RAZORPAY") await openPaymentCheckout(order, `Advertising campaign ${id}`); setMessage("Payment evidence is being verified. Campaign approval remains a separate Admin review."); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "Secure checkout could not be opened."); } finally { setBusy(false); } }
  async function submit(id: number) { setBusy(true); try { await advertisingService.submit(id); setMessage("Campaign submitted for Admin review."); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "Submission failed."); } finally { setBusy(false); } }
  return <main className="mx-auto max-w-6xl p-5 sm:p-8"><p className="text-sm font-bold uppercase tracking-wider text-orange-600">Partner advertising</p><h1 className="mt-1 text-3xl font-black text-slate-900">Promote your hotel</h1><p className="mt-2 text-slate-600">Sponsored placements are clearly labelled. Payment does not guarantee approval and never changes verification, search ranking, inventory, or booking eligibility.</p>
    {message && <p className="mt-5 rounded-xl bg-blue-50 p-3 text-sm text-blue-800">{message}</p>}
    <div className="mt-8 grid gap-6 lg:grid-cols-[.9fr_1.4fr]"><form onSubmit={create} className="space-y-4 rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-lg font-black">New campaign</h2><label className="block text-sm font-bold">Plan<select value={plan} onChange={(e) => setPlan(e.target.value)} className="mt-1 w-full rounded-lg border p-2">{config?.plans.map((p) => <option key={p.code} value={p.code}>{p.name} · {p.currency} {p.amount}</option>)}</select></label><label className="block text-sm font-bold">Start date<input type="datetime-local" required value={start} onChange={(e) => setStart(e.target.value)} className="mt-1 w-full rounded-lg border p-2" /></label>{selected?.placement === "DESTINATION_PROMOTION" && <><label className="block text-sm font-bold">District slug<input required value={district} onChange={(e) => setDistrict(e.target.value)} className="mt-1 w-full rounded-lg border p-2" /></label><label className="block text-sm font-bold">Destination slug (optional)<input value={destination} onChange={(e) => setDestination(e.target.value)} className="mt-1 w-full rounded-lg border p-2" /></label></>}<label className="block text-sm font-bold">Creative (JPEG, PNG or WebP)<input type="file" accept="image/jpeg,image/png,image/webp" required onChange={(e) => setFile(e.target.files?.[0])} className="mt-1 block w-full text-sm" /></label><label className="block text-sm font-bold">Accessible image description<input required value={alt} onChange={(e) => setAlt(e.target.value)} className="mt-1 w-full rounded-lg border p-2" /></label><button disabled={busy} className="w-full rounded-lg bg-slate-900 px-4 py-3 font-bold text-white disabled:opacity-50">Create & get payment order</button></form>
    <section className="space-y-4"><h2 className="text-lg font-black">Campaigns</h2>{items.length === 0 && <div className="rounded-2xl border bg-white p-8 text-center text-slate-500">No campaigns yet.</div>}{items.map((item) => <article key={item.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-black">{item.hotel_name} · {item.placement.replaceAll("_", " ")}</p><p className="text-sm text-slate-500">{new Date(item.start_at).toLocaleDateString()} – {new Date(item.end_at).toLocaleDateString()}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-black">{item.status.replaceAll("_", " ")}</span></div>{item.creative_url && <div className="relative mt-4 h-36 w-full overflow-hidden rounded-xl"><Image unoptimized fill sizes="(max-width: 1024px) 100vw, 55vw" src={item.creative_url} alt={item.alt_text || "Campaign creative"} className="object-cover" /></div>}<div className="mt-4 grid grid-cols-2 gap-3 text-sm sm:grid-cols-4"><p><b>Price</b><br />{item.currency} {item.price_amount}</p><p><b>Payment</b><br />{item.payment_status}</p><p><b>Impressions</b><br />{item.impressions}</p><p><b>Clicks</b><br />{item.clicks}</p></div>{item.review_reason && <p className="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-900"><b>Review note:</b> {item.review_reason}</p>}<div className="mt-4 flex flex-wrap gap-3">{item.payment_status === "PENDING" && <button disabled={busy} onClick={() => void pay(item.id)} className="rounded-lg bg-slate-900 px-4 py-2 text-sm font-bold text-white disabled:opacity-40">Open secure checkout</button>}{["DRAFT", "PAYMENT_PENDING", "NEEDS_CHANGES"].includes(item.status) && <button disabled={busy || item.payment_status !== "PAID"} onClick={() => void submit(item.id)} className="rounded-lg bg-orange-600 px-4 py-2 text-sm font-bold text-white disabled:opacity-40">Submit for review</button>}</div></article>)}</section></div></main>;
}
