"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { FormEvent, useCallback, useEffect, useState } from "react";

import { FormError } from "@/components/FormError";
import { ApiError } from "@/services/api";
import { inventoryService } from "@/services/inventory.service";
import { roomService } from "@/services/room.service";
import type { RoomInventory, RoomInventoryInput, RoomType } from "@/types/hotel";

export default function InventoryPage() {
  const { hotelId, roomId } = useParams<{ hotelId: string; roomId: string }>(); const roomTypeId = Number(roomId);
  const [room, setRoom] = useState<RoomType | null>(null); const [items, setItems] = useState<RoomInventory[]>([]); const [start, setStart] = useState(""); const [end, setEnd] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [editing, setEditing] = useState<RoomInventory | null>(null);
  const load = useCallback(async () => { await Promise.resolve(); setLoading(true); setError(""); try { const [roomData, inventory] = await Promise.all([roomService.get(roomTypeId), inventoryService.list(roomTypeId, start || undefined, end || undefined)]); if (roomData.hotel_id !== Number(hotelId)) throw new Error("Room does not belong to this hotel."); setRoom(roomData); setItems(inventory); } catch (e) { setError(e instanceof ApiError || e instanceof Error ? e.message : "Unable to load inventory."); } finally { setLoading(false); } }, [end, hotelId, roomTypeId, start]);
  // Loading remote API state is the synchronization performed by this effect.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load(); }, [load]);
  async function save(data: RoomInventoryInput) { if (editing) { await inventoryService.update(editing.id, { total_inventory: data.total_inventory, blocked_inventory: data.blocked_inventory, price: data.price, is_closed: data.is_closed }); setEditing(null); } else await inventoryService.create(roomTypeId, data); await load(); }
  return <div className="mx-auto max-w-7xl"><Link href={`/hotels/${hotelId}`} className="link">← Back to hotel</Link><div className="my-6"><p className="eyebrow">Inventory</p><h1 className="page-title">{room?.name ?? "Room inventory"}</h1><p className="page-subtitle">Manage dated capacity, closures, and pricing. Available inventory is calculated from blocked, held, and confirmed rooms.</p></div><FormError message={error} /><div className="grid gap-6 xl:grid-cols-[2fr_1fr]"><section className="panel"><form onSubmit={(e) => { e.preventDefault(); void load(); }} className="mb-5 flex flex-wrap items-end gap-3"><DateField label="Start date" value={start} onChange={setStart} /><DateField label="End date" value={end} onChange={setEnd} /><button className="btn-secondary">Apply range</button><button type="button" className="link px-2 py-2" onClick={() => { setStart(""); setEnd(""); }}>Clear</button></form>{loading ? <p className="text-slate-500">Loading inventory…</p> : items.length === 0 ? <p className="empty-state">No inventory records for this range.</p> : <div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="border-b text-xs uppercase text-slate-500"><tr>{["Date", "Total", "Available", "Blocked", "Held", "Confirmed", "Price", "Closed", ""].map((h, i) => <th key={`${h}-${i}`} className="px-3 py-3">{h}</th>)}</tr></thead><tbody className="divide-y">{items.map((item) => <tr key={item.id}><td className="px-3 py-4 whitespace-nowrap">{item.inventory_date}</td><td className="px-3 py-4">{item.total_inventory}</td><td className="px-3 py-4 font-semibold">{item.available_inventory}</td><td className="px-3 py-4">{item.blocked_inventory}</td><td className="px-3 py-4">{item.held_inventory}</td><td className="px-3 py-4">{item.confirmed_inventory}</td><td className="px-3 py-4">{room?.currency} {Number(item.price).toFixed(2)}</td><td className="px-3 py-4">{item.is_closed ? "Yes" : "No"}</td><td className="px-3 py-4"><button className="link" onClick={() => setEditing(item)}>Edit</button></td></tr>)}</tbody></table></div>}</section><section className="panel"><h2 className="section-title">{editing ? `Edit ${editing.inventory_date}` : "Add inventory"}</h2><InventoryForm key={editing?.id ?? "new"} initial={editing ?? undefined} onSave={save} onCancel={editing ? () => setEditing(null) : undefined} /></section></div></div>;
}

function InventoryForm({ initial, onSave, onCancel }: { initial?: RoomInventory; onSave: (data: RoomInventoryInput) => Promise<void>; onCancel?: () => void }) { const [error, setError] = useState(""); const [saving, setSaving] = useState(false); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); const num = (name: string) => Number(form.get(name)); const data: RoomInventoryInput = { inventory_date: String(form.get("inventory_date")), total_inventory: num("total_inventory"), blocked_inventory: num("blocked_inventory"), price: num("price"), is_closed: form.get("is_closed") === "on" }; if (data.total_inventory < 0 || data.blocked_inventory < 0) return setError("Inventory values cannot be negative."); if (data.blocked_inventory > data.total_inventory) return setError("Blocked inventory cannot exceed total inventory."); if (data.price < 0) return setError("Price cannot be negative."); if (initial && !window.confirm(`Update ${initial.inventory_date}? ${initial.held_inventory} held and ${initial.confirmed_inventory} confirmed rooms will remain protected.`)) return; setSaving(true); setError(""); try { await onSave(data); if (!initial) formElement.reset(); } catch (e) { setError(e instanceof ApiError ? e.message : "Unable to save inventory."); } finally { setSaving(false); } }
  return <form onSubmit={submit} className="mt-5 space-y-4"><FormError message={error} />{initial && <div className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900"><strong>Protected commitments</strong><p className="mt-1">Held: {initial.held_inventory} · Confirmed: {initial.confirmed_inventory} · Currently available: {initial.available_inventory}</p></div>}<SmallField label="Date" name="inventory_date" type="date" required defaultValue={initial?.inventory_date} disabled={Boolean(initial)} /><SmallField label="Total inventory" name="total_inventory" type="number" min={0} required defaultValue={initial?.total_inventory ?? 0} /><SmallField label="Blocked / maintenance" name="blocked_inventory" type="number" min={0} required defaultValue={initial?.blocked_inventory ?? 0} /><SmallField label="Price" name="price" type="number" min={0} step={0.01} required defaultValue={initial?.price ?? 0} /><label className="flex gap-2 text-sm font-semibold"><input name="is_closed" type="checkbox" defaultChecked={initial?.is_closed} /> Closed for sale</label><p className="text-xs leading-5 text-slate-500">Available inventory is recalculated by the server. Held and confirmed rooms cannot be overwritten.</p><div className="flex gap-2"><button className="btn-primary flex-1" disabled={saving}>{saving ? "Saving…" : initial ? "Update" : "Add record"}</button>{onCancel && <button type="button" className="btn-secondary" onClick={onCancel}>Cancel</button>}</div></form>; }
function DateField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label><span className="mb-1 block text-xs font-semibold text-slate-600">{label}</span><input type="date" value={value} onChange={(e) => onChange(e.target.value)} className="input w-auto" /></label>; }
function SmallField({ label, ...props }: { label: string } & React.InputHTMLAttributes<HTMLInputElement>) { return <label><span className="mb-1.5 block text-sm font-semibold">{label}</span><input {...props} className="input" /></label>; }
