"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";

import { BOOKING_STATUS, PAYMENT_STATUS, date, money, statusClasses } from "@/src/lib/account-status";
import { safariStatusClasses, safariStatusDisplay } from "@/src/lib/safari-status";
import { bookingService, type CustomerBooking, type CustomerPayment } from "@/src/services/booking.service";
import { communicationService } from "@/src/services/communication.service";
import { safariService } from "@/src/services/safari.service";
import type { SafariRequest } from "@/src/types/safari";

export function AccountDashboard() {
  const [bookings, setBookings] = useState<CustomerBooking[]>([]); const [safaris, setSafaris] = useState<SafariRequest[]>([]); const [payments, setPayments] = useState<CustomerPayment[]>([]); const [unreadMessages, setUnreadMessages] = useState(0); const [unreadNotifications, setUnreadNotifications] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); const results = await Promise.allSettled([bookingService.listMine(), safariService.mine(), bookingService.listPaymentHistory(), communicationService.listConversations(), communicationService.listNotifications()]); const [bookingResult, safariResult, paymentResult, messageResult, notificationResult] = results; if (bookingResult.status === "fulfilled") setBookings(bookingResult.value.items); if (safariResult.status === "fulfilled") setSafaris(safariResult.value); if (paymentResult.status === "fulfilled") setPayments(paymentResult.value.items); if (messageResult.status === "fulfilled") setUnreadMessages(messageResult.value.unread_count); if (notificationResult.status === "fulfilled") setUnreadNotifications(notificationResult.value.unread_count); if (results.some((result) => result.status === "rejected")) setError("Some account information could not be loaded. Retry to refresh all sections."); setLoading(false); }, []);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  const upcoming = useMemo(() => bookings.filter((item) => !["CANCELLED", "REFUNDED", "REQUEST_REJECTED", "REQUEST_EXPIRED", "CHECKED_OUT", "NO_SHOW"].includes(item.status)).sort((a, b) => a.check_in.localeCompare(b.check_in))[0], [bookings]);
  const activeSafari = safaris.find((item) => !["CONFIRMED", "NOT_AVAILABLE", "EXPIRED", "CANCELLED", "BOOKING_FAILED"].includes(item.status));
  const recentPayment = [...payments].sort((a, b) => b.created_at.localeCompare(a.created_at))[0];
  const actions = [...bookings.filter((item) => item.status === "PAYMENT_PENDING").map((item) => ({ label: `Pay for ${item.hotel.name}`, body: item.booking_reference, href: `/account/bookings/${item.booking_reference}` })), ...safaris.filter((item) => item.status === "AWAITING_TRAVELLER_DETAILS" || item.status === "PAYMENT_PENDING" || item.status === "BOOKING_FAILED").map((item) => ({ label: safariStatusDisplay(item.status).nextAction, body: `${item.safari.name} · ${item.request_reference}`, href: `/account/safaris/${item.request_reference}` }))];
  if (loading) return <DashboardSkeleton />;
  return <div><Header eyebrow="Your account" title="Travel dashboard" description="The next useful step across your Maharashtra Tourist Places bookings, Safari requests, payments, and conversations." />{error && <div role="alert" className="mb-6 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">{error} <button onClick={() => void load()} className="font-black underline">Try again</button></div>}{actions.length > 0 && <section aria-labelledby="actions-title" className="mb-8 rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 id="actions-title" className="font-black text-amber-950">Action needed</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{actions.map((action) => <Link key={`${action.href}-${action.label}`} href={action.href} className="rounded-xl border border-amber-200 bg-white p-4 hover:border-amber-300"><strong className="text-[var(--brand)]">{action.label}</strong><span className="mt-1 block text-xs text-slate-500">{action.body}</span></Link>)}</div></section>}
    <div className="grid gap-5 xl:grid-cols-2">{upcoming ? <DashboardCard title="Upcoming hotel booking" href={`/account/bookings/${upcoming.booking_reference}`} cta="View booking"><p className="text-xl font-black text-[var(--brand)]">{upcoming.hotel.name}</p><p className="mt-2 text-sm text-slate-500">{date(upcoming.check_in)} – {date(upcoming.check_out)} · {upcoming.room.name}</p><Status display={BOOKING_STATUS[upcoming.status]} /></DashboardCard> : <EmptyCard title="No active hotel booking" body="Your next confirmed stay or booking request will appear here." href="/hotels" cta="Browse hotels" />}
      {activeSafari ? <DashboardCard title="Active Safari request" href={`/account/safaris/${activeSafari.request_reference}`} cta="Track request"><p className="text-xl font-black text-[var(--brand)]">{activeSafari.safari.name}</p><p className="mt-2 text-sm text-slate-500">{activeSafari.request_reference}</p><span className={`mt-4 inline-flex rounded-full border px-3 py-1.5 text-xs font-black ${safariStatusClasses(safariStatusDisplay(activeSafari.status).tone)}`}>{safariStatusDisplay(activeSafari.status).label}</span></DashboardCard> : <EmptyCard title="No active Safari request" body="Managed availability requests and confirmations appear here." href="/safaris" cta="Explore Safaris" />}
      {recentPayment ? <DashboardCard title="Recent payment" href="/account/payments" cta="Payment history"><div className="flex items-start justify-between gap-4"><div><p className="font-black text-[var(--brand)]">{recentPayment.hotel_name}</p><p className="mt-1 text-xs text-slate-500">{recentPayment.booking_reference}</p></div><strong>{money(recentPayment.amount, recentPayment.currency)}</strong></div><Status display={PAYMENT_STATUS[recentPayment.status]} /></DashboardCard> : <EmptyCard title="No hotel payments yet" body="Verified customer payment attempts will appear here." href="/account/payments" cta="View payments" />}
      <DashboardCard title="Inbox" href={unreadMessages ? "/account/messages" : "/account/notifications"} cta="Open updates"><div className="grid grid-cols-2 gap-3"><Metric value={unreadMessages} label="Unread messages" /><Metric value={unreadNotifications} label="Unread notifications" /></div></DashboardCard></div>
  </div>;
}

export function Header({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) { return <header className="mb-8 flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">{eyebrow}</p><h1 className="page-title mt-2">{title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">{description}</p></div>{action}</header>; }
function Status({ display }: { display: { label: string; tone: "blue" | "green" | "amber" | "red" | "slate" } }) { return <span className={`mt-4 inline-flex rounded-full border px-3 py-1.5 text-xs font-black ${statusClasses(display.tone)}`}>{display.label}</span>; }
function DashboardCard({ title, href, cta, children }: { title: string; href: string; cta: string; children: React.ReactNode }) { return <section className="content-card"><h2 className="text-xs font-black uppercase tracking-[.14em] text-slate-400">{title}</h2><div className="mt-4">{children}</div><Link href={href} className="mt-5 inline-flex text-sm font-black text-[var(--accent)] hover:text-[var(--accent-strong)]">{cta} →</Link></section>; }
function EmptyCard({ title, body, href, cta }: { title: string; body: string; href: string; cta: string }) { return <DashboardCard title={title} href={href} cta={cta}><p className="text-sm leading-6 text-slate-500">{body}</p></DashboardCard>; }
function Metric({ value, label }: { value: number; label: string }) { return <div className="rounded-xl bg-[var(--surface-muted)] p-4"><strong className="text-2xl text-[var(--brand)]">{value}</strong><span className="mt-1 block text-xs text-slate-500">{label}</span></div>; }
function DashboardSkeleton() { return <div aria-label="Loading account overview"><div className="skeleton h-12 w-64 rounded" /><div className="mt-8 grid gap-5 sm:grid-cols-2">{[1,2,3,4].map((key) => <div key={key} className="skeleton h-56 rounded-2xl" />)}</div></div>; }
