"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ApiError } from "@/src/services/api";
import { BOOKING_STATUS, PAYMENT_STATUS, REFUND_STATUS, date, money, statusClasses } from "@/src/lib/account-status";
import { bookingService, type Cancellation, type CustomerBooking, type PaymentOrder, type PaymentReceipt, type ReviewData } from "@/src/services/booking.service";

export function BookingDetail({ bookingReference }: { bookingReference: string }) {
  const [booking, setBooking] = useState<CustomerBooking>(); const [payments, setPayments] = useState<PaymentOrder[]>([]); const [cancellation, setCancellation] = useState<Cancellation | null>(null); const [review, setReview] = useState<ReviewData | null>(null); const [receipt, setReceipt] = useState<PaymentReceipt | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [showCancel, setShowCancel] = useState(false); const [reason, setReason] = useState(""); const [confirmed, setConfirmed] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const summary = (await bookingService.listMine()).items.find((item) => item.booking_reference === bookingReference); if (!summary) throw new ApiError("Booking not found", 404); const [detail, history, cancel, existingReview] = await Promise.all([bookingService.getBooking(summary.id), bookingService.getPaymentHistory(summary.id), bookingService.getCancellation(summary.id), bookingService.getReview(summary.id).catch((cause) => cause instanceof ApiError && cause.status === 404 ? null : Promise.reject(cause))]); setBooking(detail); setPayments(history.items); setCancellation(cancel); setReview(existingReview); } catch (cause) { setError(cause instanceof Error ? cause.message : "This booking could not be loaded."); } finally { setLoading(false); } }, [bookingReference]);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  const primaryPayment = useMemo(() => [...payments].reverse().find((item) => item.status === "PAID") ?? payments.at(-1), [payments]);
  async function createPayment() { if (!booking) return; setBusy(true); setError(""); try { await bookingService.createPaymentOrder(booking.id); setNotice("A payment session was created through Maharashtra Tourist Places’ configured provider. Confirmation remains backend-verified."); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Payment could not be started."); } finally { setBusy(false); } }
  async function requestCancellation() { if (!booking) return; setBusy(true); setError(""); try { setCancellation(await bookingService.requestCancellation(booking.id, reason.trim())); setShowCancel(false); setNotice("Cancellation recorded. The backend-authoritative refund outcome is shown below."); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Cancellation could not be requested."); } finally { setBusy(false); } }
  async function showReceipt(item: PaymentOrder) { if (!booking) return; setBusy(true); setError(""); try { setReceipt(await bookingService.getReceipt(booking.id, item.id)); } catch (cause) { setError(cause instanceof Error ? cause.message : "Receipt is not available for this payment."); } finally { setBusy(false); } }
  if (loading) return <div className="skeleton h-[34rem] rounded-2xl" />;
  if (error && !booking) return <ErrorPanel message={error} retry={load} />;
  if (!booking) return null;
  const bookingDisplay = BOOKING_STATUS[booking.status]; const paymentDisplay = PAYMENT_STATUS[booking.payment_status];
  return <div><Link href="/account/bookings" className="text-sm font-black text-[var(--accent)]">← All hotel bookings</Link><header className="my-7"><p className="eyebrow">{booking.booking_reference}</p><h1 className="page-title mt-2">{booking.hotel.name}</h1><p className="mt-3 text-sm text-slate-500">{booking.room.name} · {date(booking.check_in)} – {date(booking.check_out)}</p><div className="mt-4 flex flex-wrap gap-2"><span className={`rounded-full border px-3 py-1.5 text-xs font-black ${statusClasses(bookingDisplay.tone)}`}>{bookingDisplay.label}</span><span className={`rounded-full border px-3 py-1.5 text-xs font-black ${statusClasses(paymentDisplay.tone)}`}>{paymentDisplay.label}</span></div></header>{notice && <p role="status" className="mb-5 rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-800">{notice}</p>}{error && <p role="alert" className="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</p>}
    <div className="grid gap-6 xl:grid-cols-[1fr_320px]"><div className="space-y-6"><Section title="Stay summary"><dl className="grid gap-4 text-sm sm:grid-cols-2"><Data label="Hotel" value={`${booking.hotel.name}, ${booking.hotel.city}`} /><Data label="Room" value={booking.room.name} /><Data label="Check-in" value={date(booking.check_in)} /><Data label="Check-out" value={date(booking.check_out)} /><Data label="Guests" value={`${booking.adults} adults · ${booking.children} children`} /><Data label="Rooms / nights" value={`${booking.rooms} room${booking.rooms === 1 ? "" : "s"} · ${booking.nights} night${booking.nights === 1 ? "" : "s"}`} /></dl>{booking.travellers?.length ? <p className="mt-5 border-t border-[var(--line)] pt-4 text-sm text-slate-600">Primary guest: <strong>{booking.travellers.find((item) => item.is_primary)?.full_name ?? booking.travellers[0]?.full_name}</strong></p> : null}</Section>
      <Section title="Booking and request status"><p className="text-sm leading-6 text-slate-600">{bookingDisplay.detail}</p>{booking.booking_mode === "BOOKING_ON_REQUEST" && <div className="mt-4 rounded-xl bg-[var(--surface-muted)] p-4 text-sm"><strong className="text-[var(--brand)]">Hotel approval booking</strong><p className="mt-1 text-slate-600">{booking.status === "PENDING" ? "The request is awaiting the hotel response. Payment is unavailable until acceptance." : booking.status === "PAYMENT_PENDING" ? "The hotel accepted this request. Complete payment before the displayed payment window ends." : booking.request_decision_reason || "The request lifecycle is recorded above."}</p>{booking.request_expires_at && booking.status === "PENDING" && <p className="mt-2 text-xs text-slate-500">Response window: {new Date(booking.request_expires_at).toLocaleString()}</p>}{booking.payment_expires_at && booking.status === "PAYMENT_PENDING" && <p className="mt-2 text-xs text-slate-500">Payment window: {new Date(booking.payment_expires_at).toLocaleString()}</p>}</div>}</Section>
      <Section title="Price captured at booking"><dl className="grid gap-3 text-sm sm:grid-cols-2"><Data label="Room subtotal" value={money(booking.subtotal, booking.currency)} /><Data label="Taxes" value={money(booking.taxes, booking.currency)} /><Data label="Platform fee" value={money(booking.platform_fee, booking.currency)} /><Data label="Discount" value={money(booking.discount, booking.currency)} /><Data label="Total" value={money(booking.total_amount, booking.currency)} strong /></dl><p className="mt-4 text-xs leading-5 text-slate-500">These are immutable booking-time amounts. Current hotel prices are not used.</p></Section>
      <Section title="Cancellation policy captured at booking"><Policy snapshot={booking.policy_snapshot} />{cancellation ? <CancellationView item={cancellation} /> : booking.status === "CONFIRMED" ? <div className="mt-5 border-t border-[var(--line)] pt-5">{showCancel ? <div className="rounded-xl border border-red-200 bg-red-50 p-4"><p className="text-sm leading-6 text-red-800">The backend calculates any refund only from this booking-time policy. Submitting is irreversible; provider processing may continue after the booking is cancelled.</p><label className="field-label mt-4 block" htmlFor="cancel-reason">Reason<input id="cancel-reason" value={reason} onChange={(event) => setReason(event.target.value)} className="field-input mt-2 bg-white" maxLength={2000} /></label><label className="mt-3 flex gap-3 text-sm text-red-900"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} />I understand that cancellation and refund outcome are determined by the backend policy snapshot.</label><div className="mt-4 flex flex-wrap gap-3"><button type="button" disabled={busy || reason.trim().length < 3 || !confirmed} onClick={() => void requestCancellation()} className="primary-button bg-red-700">{busy ? "Submitting…" : "Confirm cancellation"}</button><button type="button" onClick={() => setShowCancel(false)} className="secondary-button">Keep booking</button></div></div> : <button type="button" onClick={() => setShowCancel(true)} className="secondary-button text-red-700">Request cancellation</button>}</div> : null}</Section>
      <Section title="Payments and receipts">{payments.length ? <div className="space-y-3">{payments.map((item) => <div key={item.id} className="rounded-xl border border-[var(--line)] p-4"><div className="flex flex-wrap justify-between gap-3"><div><strong>{PAYMENT_STATUS[item.status].label}</strong><p className="mt-1 text-xs text-slate-500">Created {new Date(item.created_at).toLocaleString()}</p></div><strong>{money(item.amount, item.currency)}</strong></div>{item.status === "PAID" && <button type="button" disabled={busy} onClick={() => void showReceipt(item)} className="secondary-button mt-3 !min-h-10">View receipt</button>}</div>)}</div> : <p className="text-sm text-slate-500">No payment attempts are recorded.</p>}{receipt && <Receipt item={receipt} />}</Section></div>
      <aside className="space-y-5 xl:sticky xl:top-24"><section className="content-card"><h2 className="font-black text-[var(--brand)]">Next action</h2><p className="mt-2 text-sm leading-6 text-slate-600">{bookingDisplay.detail}</p>{booking.status === "PAYMENT_PENDING" && <button type="button" disabled={busy || primaryPayment?.status === "PENDING"} onClick={() => void createPayment()} className="primary-button mt-5 w-full">{busy ? "Starting…" : primaryPayment?.status === "FAILED" ? "Retry payment" : primaryPayment?.status === "PENDING" ? "Payment pending" : "Complete payment"}</button>}{booking.status === "CHECKED_OUT" && <Link href={`/account/reviews/${booking.booking_reference}`} className="primary-button mt-5 w-full">{review ? "View your review" : "Write verified review"}</Link>}</section><section className="content-card"><h2 className="font-black text-[var(--brand)]">Help with this booking</h2><p className="mt-2 text-sm leading-6 text-slate-600">Use the private Maharashtra Tourist Places relay or contact support with this customer-facing reference.</p><div className="mt-4 grid gap-2"><Link href={`/account/messages?booking=${encodeURIComponent(booking.booking_reference)}`} className="secondary-button w-full">Booking messages</Link><Link href={`/contact?type=BOOKING_HELP&reference=${encodeURIComponent(booking.booking_reference)}`} className="secondary-button w-full">Contact support</Link></div></section></aside></div>
  </div>;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="content-card"><h2 className="text-xl font-black text-[var(--brand)]">{title}</h2><div className="mt-5">{children}</div></section>; }
function Data({ label, value, strong = false }: { label: string; value: string; strong?: boolean }) { return <div><dt className="text-xs font-bold uppercase tracking-wide text-slate-400">{label}</dt><dd className={`mt-1 ${strong ? "text-lg font-black text-[var(--brand)]" : "font-semibold text-slate-700"}`}>{value}</dd></div>; }
function Policy({ snapshot }: { snapshot: Record<string, unknown> }) { const entries = Object.entries(snapshot).filter(([, value]) => typeof value === "string" && value); return entries.length ? <dl className="space-y-3 text-sm">{entries.map(([key, value]) => <div key={key}><dt className="font-black text-[var(--brand)]">{key.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase())}</dt><dd className="mt-1 whitespace-pre-wrap leading-6 text-slate-600">{String(value)}</dd></div>)}</dl> : <p className="text-sm text-slate-500">No customer-facing policy text was captured. A cancellation would require backend review.</p>; }
function CancellationView({ item }: { item: Cancellation }) { return <div className="mt-5 border-t border-[var(--line)] pt-5"><div className="flex flex-wrap justify-between gap-3"><strong>Cancellation: {item.status.replaceAll("_", " ").toLowerCase().replace(/\b\w/g, (letter) => letter.toUpperCase())}</strong><strong>{money(item.refundable_amount, item.refunds[0]?.currency ?? "INR")} eligible</strong></div>{item.requires_manual_review && <p className="mt-3 rounded-xl bg-amber-50 p-3 text-sm text-amber-800">The refund needs Maharashtra Tourist Places review. The booking remains cancelled while financial reconciliation continues.</p>}<div className="mt-4 space-y-3">{item.refunds.map((refund) => { const display = REFUND_STATUS[refund.status]; return <div key={refund.id} className={`rounded-xl border p-4 ${statusClasses(display.tone)}`}><div className="flex flex-wrap justify-between gap-3"><strong>{display.label}</strong><strong>{money(refund.amount, refund.currency)}</strong></div><p className="mt-1 text-xs">Initiated {new Date(refund.created_at).toLocaleString()}{refund.completed_at ? ` · Completed ${new Date(refund.completed_at).toLocaleString()}` : ""}</p>{refund.provider_refund_id && <p className="mt-1 break-all text-xs">Refund reference: {refund.provider_refund_id}</p>}</div>; })}</div></div>; }
function Receipt({ item }: { item: PaymentReceipt }) { return <div className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 p-4"><p className="text-xs font-black uppercase tracking-wide text-emerald-700">Payment receipt</p><dl className="mt-3 grid gap-3 text-sm sm:grid-cols-2"><Data label="Booking" value={item.booking_reference} /><Data label="Payment reference" value={item.payment_reference} /><Data label="Paid" value={new Date(item.paid_at).toLocaleString()} /><Data label="Amount" value={money(item.amount, item.currency)} /></dl><p className="mt-3 text-xs text-emerald-800">Durable payment record; not a tax invoice.</p></div>; }
function ErrorPanel({ message, retry }: { message: string; retry: () => Promise<void> }) { return <div role="alert" className="content-card text-center"><h1 className="text-xl font-black text-red-800">Booking unavailable</h1><p className="mt-2 text-sm text-red-700">{message}</p><button onClick={() => void retry()} className="primary-button mt-5">Try again</button></div>; }
