"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { Header } from "@/src/components/account/AccountDashboard";
import { BOOKING_STATUS, PAYMENT_STATUS, date, money, statusClasses } from "@/src/lib/account-status";
import { bookingService, type CustomerBooking } from "@/src/services/booking.service";

type Filter = "ALL" | "ACTION" | "UPCOMING" | "COMPLETED";
export function BookingList() {
  const [items, setItems] = useState<CustomerBooking[]>([]); const [filter, setFilter] = useState<Filter>("ALL"); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { setItems((await bookingService.listMine()).items); } catch (cause) { setError(cause instanceof Error ? cause.message : "Bookings could not be loaded."); } finally { setLoading(false); } }, []);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  const visible = useMemo(() => items.filter((item) => filter === "ALL" || (filter === "ACTION" && ["PAYMENT_PENDING", "CHECK_IN_ISSUE", "REFUND_PENDING"].includes(item.status)) || (filter === "UPCOMING" && ["PENDING", "PAYMENT_PENDING", "CONFIRMED", "CHECKED_IN"].includes(item.status)) || (filter === "COMPLETED" && ["CHECKED_OUT", "CANCELLED", "REFUNDED", "NO_SHOW", "REQUEST_REJECTED", "REQUEST_EXPIRED"].includes(item.status))), [filter, items]);
  return <div><Header eyebrow="Your account" title="Hotel bookings" description="Customer-owned booking requests, confirmed stays, cancellations, refunds, and verified payment state." action={<Link href="/hotels" className="secondary-button">Find a hotel</Link>} />{error && <p role="alert" className="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error} <button onClick={() => void load()} className="font-black underline">Try again</button></p>}{loading ? <div className="space-y-4">{[1,2,3].map((key) => <div key={key} className="skeleton h-48 rounded-2xl" />)}</div> : items.length === 0 ? <div className="content-card text-center"><h2 className="text-xl font-black text-[var(--brand)]">No hotel bookings yet</h2><p className="mt-2 text-sm text-slate-500">Your booking requests and confirmed stays will appear here.</p><Link href="/hotels" className="primary-button mt-5">Explore hotels</Link></div> : <><div className="mb-5 flex flex-wrap gap-2" aria-label="Filter bookings">{(["ALL", "ACTION", "UPCOMING", "COMPLETED"] as Filter[]).map((value) => <button key={value} type="button" aria-pressed={filter === value} onClick={() => setFilter(value)} className={`rounded-full border px-4 py-2 text-xs font-black ${filter === value ? "border-[var(--accent)] bg-[var(--accent-soft)] text-[var(--accent-strong)]" : "border-[var(--line)] bg-white text-slate-600"}`}>{value === "ALL" ? "All" : value === "ACTION" ? "Action needed" : value === "UPCOMING" ? "Upcoming / active" : "Completed / closed"}</button>)}</div><div className="space-y-4">{visible.map((item) => <BookingCard key={item.booking_reference} item={item} />)}{!visible.length && <p className="content-card text-center text-sm text-slate-500">No bookings match this filter.</p>}</div></>}</div>;
}
function BookingCard({ item }: { item: CustomerBooking }) { const booking = BOOKING_STATUS[item.status]; const payment = PAYMENT_STATUS[item.payment_status]; const action = item.status === "PAYMENT_PENDING" ? "Complete payment" : item.status === "REFUND_PENDING" ? "View refund status" : item.status === "CHECKED_OUT" ? "View stay / review" : "View booking"; return <article className="rounded-2xl border border-[var(--line)] bg-white p-5 shadow-[var(--shadow-sm)] sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.14em] text-[var(--accent)]">{item.booking_reference}</p><h2 className="mt-2 text-xl font-black text-[var(--brand)]">{item.hotel.name}</h2><p className="mt-2 text-sm text-slate-500">{item.room.name} · {date(item.check_in)} – {date(item.check_out)}</p><p className="mt-1 text-sm text-slate-500">{item.adults} adult{item.adults === 1 ? "" : "s"}{item.children ? ` · ${item.children} child${item.children === 1 ? "" : "ren"}` : ""} · {item.rooms} room{item.rooms === 1 ? "" : "s"}</p></div><strong>{money(item.total_amount, item.currency)}</strong></div><div className="mt-4 flex flex-wrap gap-2"><span className={`rounded-full border px-3 py-1.5 text-xs font-black ${statusClasses(booking.tone)}`}>{booking.label}</span><span className={`rounded-full border px-3 py-1.5 text-xs font-black ${statusClasses(payment.tone)}`}>{payment.label}</span>{item.booking_mode === "BOOKING_ON_REQUEST" && <span className="rounded-full border border-blue-200 bg-blue-50 px-3 py-1.5 text-xs font-black text-blue-800">Hotel approval booking</span>}</div><div className="mt-5 flex justify-end border-t border-[var(--line)] pt-4"><Link href={`/account/bookings/${item.booking_reference}`} className={item.status === "PAYMENT_PENDING" ? "primary-button !min-h-10" : "secondary-button !min-h-10"}>{action}</Link></div></article>; }
