"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { Header } from "@/src/components/account/AccountDashboard";
import { communicationService } from "@/src/services/communication.service";
import type { NotificationData } from "@/src/types/communication";

function actionFor(item: NotificationData): { href: string; label: string } | null { const booking = typeof item.data.booking_reference === "string" ? item.data.booking_reference : null; const safari = typeof item.data.safari_request_reference === "string" ? item.data.safari_request_reference : typeof item.data.request_reference === "string" ? item.data.request_reference : null; if (booking) return { href: `/account/bookings/${booking}`, label: "View booking" }; if (safari) return { href: `/account/safaris/${safari}`, label: "View Safari request" }; if (item.event_type === "MESSAGE_RECEIVED") return { href: "/account/messages", label: "View messages" }; return null; }
export function NotificationCenter() {
  const [items, setItems] = useState<NotificationData[]>([]); const [unread, setUnread] = useState(0); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const result = await communicationService.listNotifications(); setItems(result.items); setUnread(result.unread_count); } catch (cause) { setError(cause instanceof Error ? cause.message : "Notifications could not be loaded."); } finally { setLoading(false); } }, []);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  async function read(item: NotificationData) { if (item.read_at) return; setBusy(true); try { await communicationService.markNotificationRead(item.id); await load(); } finally { setBusy(false); } }
  async function readAll() { setBusy(true); try { await communicationService.markAllNotificationsRead(); await load(); } finally { setBusy(false); } }
  return <div><Header eyebrow="Your account" title="Notifications" description="Customer-safe transactional booking, payment, refund, Safari, message, and account updates. Marketing is separate." action={unread ? <button disabled={busy} onClick={() => void readAll()} className="secondary-button">Mark all read ({unread})</button> : undefined} />{error && <p role="alert" className="mb-5 rounded-xl bg-red-50 p-4 text-sm text-red-800">{error} <button onClick={() => void load()} className="font-black underline">Try again</button></p>}{loading ? <div className="space-y-3">{[1,2,3].map((key) => <div key={key} className="skeleton h-28 rounded-2xl" />)}</div> : items.length ? <div className="space-y-3">{items.map((item) => { const action = actionFor(item); return <article key={item.id} className={`rounded-2xl border p-5 ${item.read_at ? "border-[var(--line)] bg-white" : "border-blue-200 bg-blue-50/50"}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-black text-[var(--brand)]">{item.title}</h2><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-600">{item.body}</p></div><time className="text-xs text-slate-400">{new Date(item.created_at).toLocaleString()}</time></div><div className="mt-4 flex flex-wrap gap-3">{action && <Link href={action.href} className="text-sm font-black text-[var(--accent)]">{action.label} →</Link>}{!item.read_at && <button disabled={busy} onClick={() => void read(item)} className="text-sm font-black text-slate-600 underline">Mark read</button>}</div></article>; })}</div> : <div className="content-card text-center"><h2 className="text-xl font-black text-[var(--brand)]">No notifications yet</h2><p className="mt-2 text-sm text-slate-500">Transactional updates will appear here.</p></div>}</div>;
}
