"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { Header } from "@/src/components/account/AccountDashboard";
import { PAYMENT_STATUS, money, statusClasses } from "@/src/lib/account-status";
import { bookingService, type CustomerPayment, type PaymentReceipt } from "@/src/services/booking.service";

export function PaymentHistory() {
  const [items, setItems] = useState<CustomerPayment[]>([]); const [receipt, setReceipt] = useState<PaymentReceipt | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { setItems((await bookingService.listPaymentHistory()).items); } catch (cause) { setError(cause instanceof Error ? cause.message : "Payment history could not be loaded."); } finally { setLoading(false); } }, []);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  async function viewReceipt(item: CustomerPayment) { setBusy(true); setError(""); try { setReceipt(await bookingService.getReceipt(item.booking_id, item.id)); } catch (cause) { setError(cause instanceof Error ? cause.message : "Receipt is unavailable."); } finally { setBusy(false); } }
  return <div><Header eyebrow="Your account" title="Payments & receipts" description="Backend-verified hotel booking transactions owned by your account. Safari payment state remains on the related Safari request." />{error && <p role="alert" className="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error} <button className="font-black underline" onClick={() => void load()}>Try again</button></p>}{loading ? <div className="space-y-4">{[1,2].map((key) => <div key={key} className="skeleton h-40 rounded-2xl" />)}</div> : items.length ? <div className="space-y-4">{items.map((item) => { const display = PAYMENT_STATUS[item.status]; return <article key={item.id} className="content-card"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-wide text-[var(--accent)]">Hotel booking payment</p><h2 className="mt-2 text-lg font-black text-[var(--brand)]">{item.hotel_name}</h2><Link href={`/account/bookings/${item.booking_reference}`} className="mt-1 block text-sm font-bold text-[var(--accent)]">{item.booking_reference}</Link><p className="mt-2 text-xs text-slate-500">{new Date(item.verified_at ?? item.created_at).toLocaleString()}</p></div><div className="text-right"><strong>{money(item.amount, item.currency)}</strong><span className={`mt-3 block rounded-full border px-3 py-1.5 text-xs font-black ${statusClasses(display.tone)}`}>{display.label}</span></div></div>{item.status === "PAID" && <button disabled={busy} onClick={() => void viewReceipt(item)} className="secondary-button mt-5 !min-h-10">View receipt</button>}</article>; })}</div> : <div className="content-card text-center"><h2 className="text-xl font-black text-[var(--brand)]">No hotel payments yet</h2><p className="mt-2 text-sm text-slate-500">Verified payment attempts will appear here.</p></div>}{receipt && <section role="dialog" aria-label="Payment receipt" className="content-card mt-5 border-emerald-200"><div className="flex items-start justify-between gap-4"><div><p className="eyebrow">Payment receipt</p><h2 className="mt-2 text-xl font-black text-[var(--brand)]">{receipt.booking_reference}</h2></div><button type="button" aria-label="Close receipt" onClick={() => setReceipt(null)} className="text-xl">×</button></div><dl className="mt-5 grid gap-4 text-sm sm:grid-cols-2"><Item label="Hotel" value={receipt.hotel_name} /><Item label="Payment reference" value={receipt.payment_reference} /><Item label="Paid" value={new Date(receipt.paid_at).toLocaleString()} /><Item label="Amount" value={money(receipt.amount, receipt.currency)} /><Item label="Status" value={PAYMENT_STATUS[receipt.payment_status].label} /></dl><p className="mt-4 text-xs text-slate-500">This is the existing durable payment record, not a frontend-generated tax invoice.</p></section>}</div>;
}
function Item({ label, value }: { label: string; value: string }) { return <div><dt className="field-label">{label}</dt><dd className="mt-1 break-words font-bold text-slate-700">{value}</dd></div>; }
