"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { PartnerStatus } from "@/src/components/partner/PartnerStatus";
import { communicationService } from "@/src/services/communication.service";
import { partnerService } from "@/src/services/partner.service";
import type { CustomerBooking } from "@/src/services/booking.service";
import type { BookingGatewayState, OperationBoard, PartnerOverview, PartnerRoomType, SettlementData } from "@/src/types/partner";

type DashboardData = { overview:PartnerOverview; rooms:PartnerRoomType[]; gateway:BookingGatewayState|null; operations:OperationBoard|null; settlements:SettlementData[]; requests:CustomerBooking[]; unread:number };
export default function PartnerDashboardPage() {
  const [data,setData]=useState<DashboardData|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const load=useCallback(async()=>{setError("");try{const overview=await partnerService.getOverview();if(!overview.has_hotel){window.location.replace("/partner/onboarding");return;}const [rooms,gateway,operations,settlements,requests,notifications]=await Promise.all([partnerService.getRoomTypes().catch(()=>[]),partnerService.getBookingGateway().catch(()=>null),partnerService.getOperationsBoard().catch(()=>null),partnerService.getSettlements().catch(()=>[]),partnerService.getBookings().then(result=>result.items).catch(()=>[]),communicationService.listNotifications().catch(()=>({items:[],total:0,unread_count:0}))]);setData({overview,rooms,gateway,operations,settlements,requests,unread:notifications.unread_count});}catch(cause){setError(cause instanceof Error?cause.message:"The partner dashboard could not be loaded.");}finally{setLoading(false);}},[]);
  useEffect(()=>{queueMicrotask(()=>void load());},[load]);
  const actionable=useMemo(()=>data?.requests.filter(item=>item.booking_mode==="BOOKING_ON_REQUEST"&&item.status==="PENDING").length??0,[data]);
  if(loading)return <main className="mx-auto max-w-7xl p-6"><div className="skeleton h-44 rounded-2xl"/><div className="mt-5 grid gap-4 md:grid-cols-3">{[1,2,3].map(key=><div key={key} className="skeleton h-32 rounded-2xl"/>)}</div></main>;
  return <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">Partner workspace</p><h1 className="page-title mt-3">{data?.overview.hotel?.name??"Hotel dashboard"}</h1><p className="mt-2 text-sm text-slate-600">Manage your property, availability, guests, and Maharashtra Tourist Places operations from one place.</p></div><button className="secondary-button" onClick={()=>void load()}>Refresh</button></div>{error&&<p role="alert" className="mt-6 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</p>}{data&&<><section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Booking requests" value={actionable} note="Awaiting your response" href="/partner/bookings"/><Metric label="Today’s arrivals" value={data.operations?.arrivals.length??0} note="Operational check-ins" href="/partner/operations"/><Metric label="Rooms needing action" value={data.rooms.filter(room=>["DRAFT","PENDING","NEEDS_CHANGES"].includes(room.status)).length} note={`${data.rooms.length} room types total`} href="/partner/rooms"/><Metric label="Open settlements" value={data.settlements.filter(item=>item.status!=="SETTLED").length} note={`${data.unread} unread notifications`} href="/partner/settlements"/></section><section className="mt-6 grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><div className="content-card"><div className="flex items-center justify-between gap-4"><div><h2 className="text-xl font-black text-[var(--brand)]">Launch and booking readiness</h2><p className="mt-1 text-sm text-slate-500">Payment, review and publication remain separate controls.</p></div><Link href="/partner/verification" className="secondary-button">View verification</Link></div><div className="mt-6 grid gap-4 sm:grid-cols-3"><State label="Hotel" value={data.overview.hotel?.status}/><State label="Verification" value={data.overview.verification?.verification_status}/><State label="Booking mode" value={data.gateway?.effective_status}/></div>{data.gateway?.inventory_freshness_reason&&<p className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">{data.gateway.inventory_freshness_reason}</p>}</div><div className="content-card"><h2 className="text-xl font-black text-[var(--brand)]">Quick actions</h2><div className="mt-4 grid gap-2"><Action href="/partner/inventory" label="Update inventory and rates"/><Action href="/partner/bookings" label="Review booking requests"/><Action href="/partner/property" label="Edit property profile"/><Action href="/partner/advertising" label="Manage advertising"/></div></div></section></>}</main>;
}
function Metric({label,value,note,href}:{label:string;value:number;note:string;href:string}){return <Link href={href} className="rounded-2xl border border-[var(--line)] bg-white p-5 transition hover:border-[var(--accent)]"><p className="text-xs font-black uppercase tracking-wider text-slate-500">{label}</p><p className="mt-3 text-3xl font-black text-[var(--brand)]">{value}</p><p className="mt-1 text-xs text-slate-500">{note}</p></Link>}
function State({label,value}:{label:string;value:string|null|undefined}){return <div className="rounded-xl bg-[var(--surface-muted)] p-4"><p className="mb-2 text-xs font-black uppercase tracking-wider text-slate-500">{label}</p><PartnerStatus value={value}/></div>}
function Action({href,label}:{href:string;label:string}){return <Link href={href} className="flex items-center justify-between rounded-xl border border-[var(--line)] px-4 py-3 text-sm font-bold text-[var(--brand)] hover:bg-[var(--surface-muted)]"><span>{label}</span><span aria-hidden="true">→</span></Link>}
