"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";

import { ApiError } from "@/src/services/api";
import { partnerService } from "@/src/services/partner.service";
import type { SettlementData, SettlementStatus } from "@/src/types/partner";

const tone: Record<SettlementStatus, string> = { ELIGIBLE: "bg-emerald-50 text-emerald-700", PROCESSING: "bg-sky-50 text-sky-700", SETTLED: "bg-slate-100 text-slate-700", ON_HOLD: "bg-amber-50 text-amber-800", RECONCILIATION_REQUIRED: "bg-red-50 text-red-800" };
const money = (value: string, currency: string) => new Intl.NumberFormat("en-IN", { style: "currency", currency }).format(Number(value));
const when = (value: string | null) => value ? new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";

export default function PartnerSettlementsPage() {
  const [items, setItems] = useState<SettlementData[]>([]);
  const [selected, setSelected] = useState<SettlementData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [unauthorized, setUnauthorized] = useState(false);
  const load = useCallback(async () => { setError(""); try { const data = await partnerService.getSettlements(); setItems(data); if (selected) setSelected(data.find((item) => item.id === selected.id) ?? null); } catch (cause) { setUnauthorized(cause instanceof ApiError && [401, 403].includes(cause.status)); setError(cause instanceof Error ? cause.message : "Settlement history could not be loaded."); } finally { setLoading(false); } }, [selected]);
  useEffect(() => { queueMicrotask(() => void load()); }, []); // eslint-disable-line react-hooks/exhaustive-deps

  if (loading) return <main className="mx-auto max-w-6xl p-8"><div className="h-32 animate-pulse rounded-2xl bg-white" /></main>;
  if (unauthorized) return <main className="mx-auto max-w-xl p-8 text-center"><h1 className="text-2xl font-black text-[#0b163d]">Hotel access required</h1><p className="mt-2 text-slate-500">Sign in with the partner account linked to this property.</p><Link className="primary-button mt-5" href="/partner/login">Partner sign in</Link></main>;
  return <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><Link href="/partner/dashboard" className="text-sm font-black text-[#172554] hover:underline">← Partner dashboard</Link><p className="mt-6 text-xs font-black uppercase tracking-[.16em] text-[#d95025]">Finance</p><h1 className="mt-2 text-3xl font-black text-[#0b163d]">Settlement history</h1><p className="mt-2 text-sm text-slate-500">Completed stays and finalized no-shows become eligible after the configured review window.</p></div><button className="secondary-button" onClick={() => void load()}>Refresh</button></div>
    {error && <div role="alert" className="mt-6 rounded-xl border border-red-200 bg-red-50 p-4 text-red-700">{error}</div>}
    <div className="mt-7 grid gap-6 lg:grid-cols-[1.15fr_.85fr]">
      <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">{items.length === 0 ? <p className="p-12 text-center text-sm text-slate-400">No completed stays have reached settlement eligibility yet.</p> : <div className="divide-y divide-slate-100">{items.map((item) => <button key={item.id} onClick={() => setSelected(item)} className="flex w-full items-center justify-between gap-4 p-5 text-left hover:bg-slate-50"><span><strong className="text-[#0b163d]">{item.booking.booking_reference}</strong><span className="mt-1 block text-xs text-slate-500">Eligible {when(item.eligibility_date)}</span></span><span className="text-right"><strong className="block">{money(item.net_payable, item.currency)}</strong><span className={`mt-1 inline-flex rounded-full px-2 py-1 text-[11px] font-black ${tone[item.status]}`}>{item.status.replaceAll("_", " ")}</span></span></button>)}</div>}</section>
      <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">{selected ? <SettlementDetail item={selected} /> : <p className="py-12 text-center text-sm text-slate-400">Select a settlement to see its immutable financial breakdown and timeline.</p>}</section>
    </div>
  </main>;
}

function SettlementDetail({ item }: { item: SettlementData }) { const commission = item.commission_rate === null ? "Not configured" : `${(Number(item.commission_rate) * 100).toFixed(2)}%`; return <><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase text-slate-400">Settlement #{item.id}</p><h2 className="mt-1 text-xl font-black text-[#0b163d]">{item.booking.booking_reference}</h2><p className="mt-1 text-xs text-slate-500">{item.booking.check_in} → {item.booking.check_out} · {item.booking.status.replaceAll("_", " ")}</p></div><span className={`rounded-full px-2 py-1 text-xs font-black ${tone[item.status]}`}>{item.status.replaceAll("_", " ")}</span></div>{item.hold_reason && <p className="mt-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-800">{item.hold_reason}</p>}<dl className="mt-5 space-y-3 text-sm"><Row label="Gross eligible amount" value={money(item.gross_amount, item.currency)} /><Row label={`Maharashtra Tourist Places commission (${commission})`} value={`− ${money(item.vayora_fee, item.currency)}`} /><Row label="Refund deductions" value={`− ${money(item.refund_deductions, item.currency)}`} /><Row label="Adjustments" value={money(item.adjustment_total, item.currency)} /><Row label="Net payout" value={money(item.net_payable, item.currency)} strong /><Row label="Eligible from" value={when(item.eligibility_date)} /></dl><div className="mt-6 border-t pt-5 text-sm"><p><strong>Payout status:</strong> {item.payout?.status.replaceAll("_", " ") ?? "Not initiated"}</p><p className="mt-1 text-slate-500">{item.payout?.completed_at ? `Paid ${when(item.payout.completed_at)}` : item.payout?.initiated_at ? `Initiated ${when(item.payout.initiated_at)}` : "Awaiting payout instruction"}</p>{item.payout?.provider_utr && <p className="mt-1 text-slate-500">Bank reference: {item.payout.provider_utr}</p>}{item.payout?.failure_reason && <p className="mt-2 text-red-700">{item.payout.failure_reason}</p>}{item.payout?.reconciliation_reason && <p className="mt-2 text-amber-700">{item.payout.reconciliation_reason}</p>}</div>{item.adjustments.length > 0 && <><h3 className="mt-6 font-black text-[#0b163d]">Corrections</h3><ul className="mt-3 space-y-2">{item.adjustments.map((entry) => <li key={entry.id} className="rounded-lg bg-slate-50 p-3 text-xs"><strong>{entry.kind}: {money(entry.amount, item.currency)}</strong><p className="mt-1 text-slate-500">{entry.reason}{!entry.applies_to_current_settlement ? entry.applied_to_settlement_id ? ` · Applied to settlement #${entry.applied_to_settlement_id}` : " · Applies to a future settlement" : ""}</p></li>)}</ul></>}<h3 className="mt-6 font-black text-[#0b163d]">Audit timeline</h3><ol className="mt-3 space-y-3">{item.events.map((event) => <li key={event.id} className="border-l-2 border-slate-200 pl-3 text-xs"><strong>{event.new_status.replaceAll("_", " ")}</strong><p className="mt-1 text-slate-500">{event.note} · {when(event.created_at)}</p></li>)}</ol></>; }
function Row({ label, value, strong = false }: { label: string; value: string; strong?: boolean }) { return <div className={`flex justify-between gap-3 ${strong ? "border-t pt-3 text-base font-black" : ""}`}><dt className="text-slate-500">{label}</dt><dd>{value}</dd></div>; }
