"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { FormError } from "@/components/FormError";
import { StatusBadge } from "@/components/StatusBadge";
import { ApiError } from "@/services/api";
import { discoveryService } from "@/services/discovery.service";
import type { AdminDestination, AdminPlace, DiscoveryReference, LifecycleStatus } from "@/types/discovery";

export default function PlacesPage() {
  const [items, setItems] = useState<AdminPlace[]>([]); const [reference, setReference] = useState<DiscoveryReference | null>(null); const [destinations, setDestinations] = useState<AdminDestination[]>([]); const [search, setSearch] = useState(""); const [lifecycle, setLifecycle] = useState<LifecycleStatus | "">(""); const [districtId, setDistrictId] = useState(0); const [destinationId, setDestinationId] = useState(0); const [interestId, setInterestId] = useState(0); const [applied, setApplied] = useState({query: "", lifecycle: "" as LifecycleStatus | "", districtId: 0, destinationId: 0, interestId: 0}); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  async function load() { setLoading(true); setError(""); try { const [result, ref] = await Promise.all([discoveryService.places({query: applied.query || undefined, lifecycle: applied.lifecycle || undefined, district_id: applied.districtId || undefined, destination_id: applied.destinationId || undefined, interest_id: applied.interestId || undefined}), reference ? Promise.resolve(reference) : discoveryService.reference()]); setItems(result.items); setReference(ref); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Unable to load places."); } finally { setLoading(false); } }
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
  useEffect(() => { void load(); }, [applied]);
  async function changeDistrict(value: number) { setDistrictId(value); setDestinationId(0); setDestinations(value ? await discoveryService.destinationsForDistrict(value) : []); }
  function filter(event: FormEvent) { event.preventDefault(); setApplied({query: search.trim(), lifecycle, districtId, destinationId, interestId}); }
  return <div className="mx-auto max-w-7xl"><div className="mb-7 flex flex-wrap items-center justify-between gap-4"><div><p className="eyebrow">Discovery management</p><h1 className="page-title">Places</h1><p className="page-subtitle">Manage curated and admin-authored places without changing stable public URLs.</p></div><Link href="/discovery/places/new" className="btn-primary">New place</Link></div>
    <form onSubmit={filter} className="panel grid gap-3 md:grid-cols-3 xl:grid-cols-[1fr_190px_190px_190px_170px_auto]"><label className="text-sm font-bold">Search<input value={search} onChange={(event) => setSearch(event.target.value)} className="input mt-2" placeholder="Name or slug" /></label><label className="text-sm font-bold">District<select value={districtId} onChange={(event) => void changeDistrict(Number(event.target.value))} className="input mt-2"><option value={0}>All districts</option>{reference?.districts.map((value) => <option value={value.id} key={value.id}>{value.name}</option>)}</select></label><label className="text-sm font-bold">Destination<select disabled={!districtId} value={destinationId} onChange={(event) => setDestinationId(Number(event.target.value))} className="input mt-2"><option value={0}>All destinations</option>{destinations.map((value) => <option value={value.id} key={value.id}>{value.name}</option>)}</select></label><label className="text-sm font-bold">Interest<select value={interestId} onChange={(event) => setInterestId(Number(event.target.value))} className="input mt-2"><option value={0}>All interests</option>{reference?.interests.map((value) => <option value={value.id} key={value.id}>{value.name}</option>)}</select></label><label className="text-sm font-bold">Lifecycle<select value={lifecycle} onChange={(event) => setLifecycle(event.target.value as LifecycleStatus | "")} className="input mt-2"><option value="">All</option><option>DRAFT</option><option>PUBLISHED</option><option>UNPUBLISHED</option></select></label><button className="btn-primary self-end">Apply</button></form><div className="mt-4"><FormError message={error} /></div>
    {loading ? <div className="panel mt-5">Loading places…</div> : <div className="panel mt-5 overflow-x-auto p-0"><table className="min-w-full text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{["Place","District / destination","Interests","Status","Media","Updated","Action"].map((value) => <th className="px-4 py-3" key={value}>{value}</th>)}</tr></thead><tbody className="divide-y">{items.map((item) => <tr key={item.id}><td className="px-4 py-4"><strong>{item.name}</strong><span className="block text-xs text-slate-500">{item.slug} · {item.content_source}{item.admin_overridden ? " override" : ""}</span></td><td className="px-4 py-4">{item.district_name}{item.destination_name ? ` / ${item.destination_name}` : ""}</td><td className="px-4 py-4 text-xs">{item.interests.map((value) => value.name).join(", ") || "Unclassified"}</td><td className="px-4 py-4"><StatusBadge status={item.status} /></td><td className="px-4 py-4">{item.media_asset_id ? "Specific asset" : "Fallback"}</td><td className="px-4 py-4 whitespace-nowrap">{new Date(item.updated_at).toLocaleDateString()}</td><td className="px-4 py-4"><Link href={`/discovery/places/${item.id}`} className="link">Edit / preview</Link></td></tr>)}</tbody></table>{!items.length && <p className="p-8 text-center text-slate-500">No places match these filters.</p>}</div>}
  </div>;
}
