"use client";

import Image from "next/image";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ApiError } from "@/src/services/api";
import { advertisingService } from "@/src/services/advertising.service";
import { useAuth } from "@/src/context/AuthContext";
import { openPaymentCheckout } from "@/src/lib/payment-checkout";
import type { AdvertiserProfile, AdvertisingConfig, Campaign } from "@/src/types/advertising";

const emptyProfile = { business_name: "", contact_person: "", business_email: "", phone: "", category: "", description: "", website: "" };

export default function AdvertiserWorkspace() {
  const router = useRouter(); const { user, loading } = useAuth();
  const [profile, setProfile] = useState<AdvertiserProfile>(); const [profileForm, setProfileForm] = useState(emptyProfile);
  const [config, setConfig] = useState<AdvertisingConfig>(); const [items, setItems] = useState<Campaign[]>([]);
  const [form, setForm] = useState({ campaign_name: "", headline: "", short_copy: "", target_url: "https://", plan_code: "", start_at: "", district_slug: "", destination_slug: "", alt_text: "", creative_source: "" });
  const [file, setFile] = useState<File>(); const [rights, setRights] = useState(false); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const nextConfig = await advertisingService.advertiserConfig(); setConfig(nextConfig); setForm((current) => ({ ...current, plan_code: current.plan_code || nextConfig.plans[0]?.code || "" })); try { const nextProfile = await advertisingService.advertiserProfile(); setProfile(nextProfile); setProfileForm({ business_name: nextProfile.business_name, contact_person: nextProfile.contact_person, business_email: nextProfile.business_email, phone: nextProfile.phone, category: nextProfile.category, description: nextProfile.description || "", website: nextProfile.website || "" }); setItems(await advertisingService.advertiserCampaigns()); } catch (error) { if (!(error instanceof ApiError) || error.status !== 404) throw error; } }, []);
  useEffect(() => { if (!loading && !user) router.replace("/login?next=/advertiser"); else if (!loading && user && !["CUSTOMER", "USER"].includes(user.role)) router.replace(user.role === "HOTEL_PARTNER" ? "/partner/advertising" : "/"); else if (user) queueMicrotask(() => void load().catch((error: unknown) => setMessage(error instanceof Error ? error.message : "Could not open advertiser workspace."))); }, [load, loading, router, user]);
  async function saveProfile(event: FormEvent) { event.preventDefault(); setBusy(true); try { const saved = await advertisingService.saveAdvertiserProfile({ ...profileForm, description: profileForm.description || undefined, website: profileForm.website || undefined }); setProfile(saved); setMessage("Advertiser profile saved."); } catch (error) { setMessage(error instanceof Error ? error.message : "Profile could not be saved."); } finally { setBusy(false); } }
  async function createCampaign(event: FormEvent) { event.preventDefault(); if (!file || !rights) return setMessage("Choose a creative and confirm you are authorized to use it."); setBusy(true); try { const campaign = await advertisingService.createExternal({ ...form, start_at: new Date(form.start_at).toISOString(), district_slug: form.district_slug || undefined, destination_slug: form.destination_slug || undefined, alt_text: form.alt_text || undefined, creative_source: form.creative_source || undefined, creative_rights_confirmed: true }); await advertisingService.uploadExternal(campaign.id, file, form.alt_text, form.creative_source); const order = await advertisingService.payExternal(campaign.id); if (order.provider === "RAZORPAY") await openPaymentCheckout(order, `Advertising campaign ${campaign.id}`); setMessage("Campaign created. Payment verification and Maharashtra Tourist Places review are separate steps."); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Campaign could not be created."); } finally { setBusy(false); } }
  async function pay(id: number) { setBusy(true); try { const order = await advertisingService.payExternal(id); if (order.provider === "RAZORPAY") await openPaymentCheckout(order, `Advertising campaign ${id}`); setMessage("Payment is being verified; this does not approve the campaign."); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Checkout could not be opened."); } finally { setBusy(false); } }
  async function submit(id: number) { setBusy(true); try { await advertisingService.submitExternal(id); setMessage("Campaign submitted for Maharashtra Tourist Places review."); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Campaign could not be submitted."); } finally { setBusy(false); } }
  if (loading || !user) return <main className="container-shell py-16"><p>Opening advertiser workspace…</p></main>;
  return <main className="container-shell py-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-black uppercase tracking-[.16em] text-orange-600">Advertiser workspace</p><h1 className="mt-2 text-3xl font-black">Campaign management</h1><p className="mt-2 text-slate-600">Payment, Maharashtra Tourist Places approval, and campaign activation are independent states.</p></div><Link href="/advertise" className="secondary-button">Advertising standards</Link></div>{message && <p role="status" className="mt-5 rounded-xl bg-blue-50 p-3 text-sm text-blue-900">{message}</p>}
    {!profile ? <form onSubmit={saveProfile} className="mt-8 grid gap-4 rounded-2xl border bg-white p-6 sm:grid-cols-2"><h2 className="text-xl font-black sm:col-span-2">Create your business profile</h2>{([['business_name','Business or entity name'],['contact_person','Contact person'],['business_email','Business email'],['phone','Phone in +country format'],['category','Business category'],['website','Website (HTTPS, optional)']] as const).map(([key,label]) => <label key={key} className="text-sm font-bold">{label}<input required={key !== 'website'} type={key === 'business_email' ? 'email' : key === 'website' ? 'url' : 'text'} value={profileForm[key]} onChange={(event) => setProfileForm((value) => ({ ...value, [key]: event.target.value }))} className="mt-1 w-full rounded-xl border p-3" /></label>)}<label className="text-sm font-bold sm:col-span-2">Business description<textarea value={profileForm.description} onChange={(event) => setProfileForm((value) => ({ ...value, description: event.target.value }))} className="mt-1 min-h-28 w-full rounded-xl border p-3" /></label><button disabled={busy} className="primary-button sm:col-span-2">Save advertiser profile</button></form> : <><div className="mt-8 rounded-2xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-black">{profile.business_name}</h2><p className="text-sm text-slate-500">{profile.category} · {profile.contact_person}</p></div><span className={`rounded-full px-3 py-1 text-xs font-black ${profile.status === 'ACTIVE' ? 'bg-emerald-100 text-emerald-800' : 'bg-red-100 text-red-800'}`}>{profile.status}</span></div>{profile.suspended_reason && <p className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-800">{profile.suspended_reason}</p>}</div>
    <div className="mt-8 grid gap-6 lg:grid-cols-[.9fr_1.3fr]"><form onSubmit={createCampaign} className="space-y-4 rounded-2xl border bg-white p-5"><h2 className="text-xl font-black">New campaign</h2>{([['campaign_name','Internal campaign name'],['headline','Customer-facing headline'],['target_url','Public HTTPS destination'],['alt_text','Accessible image description'],['creative_source','Creative source / provenance']] as const).map(([key,label]) => <label key={key} className="block text-sm font-bold">{label}<input required={!['creative_source'].includes(key)} type={key === 'target_url' ? 'url' : 'text'} value={form[key]} onChange={(event) => setForm((value) => ({ ...value, [key]: event.target.value }))} className="mt-1 w-full rounded-xl border p-3" /></label>)}<label className="block text-sm font-bold">Short copy<textarea required maxLength={280} value={form.short_copy} onChange={(event) => setForm((value) => ({ ...value, short_copy: event.target.value }))} className="mt-1 min-h-24 w-full rounded-xl border p-3" /></label><label className="block text-sm font-bold">Plan<select value={form.plan_code} onChange={(event) => setForm((value) => ({ ...value, plan_code: event.target.value }))} className="mt-1 w-full rounded-xl border p-3">{config?.plans.map((plan) => <option key={plan.code} value={plan.code}>{plan.name} · {plan.currency} {plan.amount}</option>)}</select></label><label className="block text-sm font-bold">Requested start<input type="datetime-local" required value={form.start_at} onChange={(event) => setForm((value) => ({ ...value, start_at: event.target.value }))} className="mt-1 w-full rounded-xl border p-3" /></label>{config?.plans.find((plan) => plan.code === form.plan_code)?.placement === 'DESTINATION_PROMOTION' && <><label className="block text-sm font-bold">District slug<input required value={form.district_slug} onChange={(event) => setForm((value) => ({ ...value, district_slug: event.target.value }))} className="mt-1 w-full rounded-xl border p-3" /></label><label className="block text-sm font-bold">Destination slug (optional)<input value={form.destination_slug} onChange={(event) => setForm((value) => ({ ...value, destination_slug: event.target.value }))} className="mt-1 w-full rounded-xl border p-3" /></label></>}<label className="block text-sm font-bold">Creative (JPEG, PNG, WebP; minimum 640×360)<input type="file" required accept="image/jpeg,image/png,image/webp" onChange={(event) => setFile(event.target.files?.[0])} className="mt-2 block w-full" /></label><label className="flex gap-3 text-sm"><input type="checkbox" checked={rights} onChange={(event) => setRights(event.target.checked)} className="mt-1" /><span>I confirm I have the rights or authorization to use this creative. This is an attestation, not independent verification by Maharashtra Tourist Places.</span></label><button disabled={busy || profile.status !== 'ACTIVE'} className="primary-button w-full">Create campaign & payment order</button></form>
    <section className="space-y-4"><h2 className="text-xl font-black">Your campaigns</h2>{items.length === 0 && <p className="rounded-2xl border bg-white p-8 text-center text-slate-500">No campaigns yet.</p>}{items.map((item) => <article key={item.id} className="rounded-2xl border bg-white p-5"><div className="flex justify-between gap-3"><div><h3 className="font-black">{item.campaign_name}</h3><p className="text-sm text-slate-500">{item.placement.replaceAll('_',' ')} · {new Date(item.start_at).toLocaleDateString()}–{new Date(item.end_at).toLocaleDateString()}</p></div><span className="h-fit rounded-full bg-slate-100 px-3 py-1 text-xs font-black">{item.status.replaceAll('_',' ')}</span></div>{item.creative_url && <div className="relative mt-4 h-40 overflow-hidden rounded-xl"><Image unoptimized fill sizes="(max-width:1024px) 100vw, 55vw" src={item.creative_url} alt={item.alt_text || 'Campaign creative'} className="object-cover" /></div>}<p className="mt-3 font-bold">{item.headline}</p><p className="text-sm text-slate-600">{item.short_copy}</p><div className="mt-4 grid grid-cols-2 gap-3 text-sm sm:grid-cols-4"><p><b>Payment</b><br />{item.payment_status}</p><p><b>Price</b><br />{item.currency} {item.price_amount}</p><p><b>Impressions</b><br />{item.impressions}</p><p><b>Clicks</b><br />{item.clicks}</p></div>{item.review_reason && <p className="mt-3 rounded-lg bg-amber-50 p-3 text-sm text-amber-900"><b>Review note:</b> {item.review_reason}</p>}{item.refund_review_required && <p className="mt-3 rounded-lg bg-blue-50 p-3 text-sm text-blue-900">This paid rejection requires an operational refund-policy review. No automatic refund action has been taken.</p>}<div className="mt-4 flex flex-wrap gap-2">{item.payment_status === 'PENDING' && <button type="button" disabled={busy} onClick={() => void pay(item.id)} className="secondary-button">Open secure checkout</button>}{['DRAFT','PAYMENT_PENDING','NEEDS_CHANGES','REJECTED'].includes(item.status) && <button type="button" disabled={busy || item.payment_status !== 'PAID'} onClick={() => void submit(item.id)} className="primary-button">Submit for review</button>}</div></article>)}</section></div></>}</main>;
}
