export type ConversationKind = "PRE_BOOKING" | "BOOKING" | "OPERATIONAL" | "DISPUTE";

export interface MessageData { id: number; sender: string; is_mine: boolean; body: string; created_at: string; }
export interface ConversationData { id: number; hotel_id: number; hotel_name: string; booking_id: number | null; booking_reference: string | null; subject: string; kind: ConversationKind; status: "OPEN" | "CLOSED"; unread_count: number; last_message_at: string | null; created_at: string; updated_at: string; messages: MessageData[]; }
export interface ConversationList { items: ConversationData[]; total: number; unread_count: number; }
export type NotificationEventType = "BOOKING_REQUEST_CREATED" | "BOOKING_REQUEST_ACCEPTED" | "BOOKING_REQUEST_REJECTED" | "BOOKING_REQUEST_EXPIRED" | "PAYMENT_REQUIRED" | "BOOKING_CONFIRMATION" | "PAYMENT_SUCCESS" | "PAYMENT_FAILURE" | "PAYMENT_RECONCILIATION" | "CANCELLATION" | "REFUND_INITIATED" | "REFUND_PROCESSING" | "REFUND_COMPLETED" | "REFUND_FAILED" | "REFUND_REQUIRES_REVIEW" | "CHECK_IN" | "CHECK_OUT" | "CHECK_IN_REMINDER" | "CHECK_OUT_REMINDER" | "NO_SHOW" | "HOTEL_OPERATIONAL_ISSUE" | "MESSAGE_RECEIVED" | "DISPUTE" | "SETTLEMENT_UPDATE" | "PAYOUT_INITIATED" | "PAYOUT_COMPLETED" | "PAYOUT_FAILED" | "PAYOUT_REQUIRES_REVIEW" | "VERIFICATION_PAYMENT_SUCCESS" | "VERIFICATION_CHANGES_REQUESTED" | "VERIFICATION_APPROVED" | "VERIFICATION_REJECTED" | "ADVERTISING_PAYMENT_SUCCESS" | "ADVERTISING_CHANGES_REQUESTED" | "ADVERTISING_APPROVED" | "ADVERTISING_REJECTED" | "ADVERTISING_PAUSED" | "SAFARI_REQUEST_RECEIVED" | "SAFARI_AVAILABILITY_UPDATE" | "SAFARI_DETAILS_REQUIRED" | "SAFARI_PAYMENT_REQUIRED" | "SAFARI_PAYMENT_RECEIVED" | "SAFARI_BOOKING_CONFIRMED" | "SAFARI_BOOKING_FAILED" | "REVIEW_RECEIVED" | "REVIEW_CHALLENGED" | "SUPPORT_ENQUIRY_RECEIVED" | "PASSWORD_RESET" | "EMAIL_VERIFICATION" | "PASSWORD_CHANGED";
export interface NotificationJob { id: number; channel: "EMAIL" | "SMS" | "WHATSAPP"; status: "PENDING" | "SENT" | "FAILED" | "PROVIDER_UNAVAILABLE"; provider: string | null; attempts: number; last_error: string | null; next_retry_at: string | null; sent_at: string | null; }
export interface NotificationData { id: number; event_type: NotificationEventType; title: string; body: string; data: Record<string, unknown>; read_at: string | null; created_at: string; jobs: NotificationJob[]; }
export interface NotificationList { items: NotificationData[]; total: number; unread_count: number; }
