"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { AdminShell } from "@/components/AdminShell";
import { controlService, type AuditLog } from "@/services/control.service";

export default function AuditPage(){return <AdminShell><Audit/></AdminShell>}
function Audit(){const [items,setItems]=useState<AuditLog[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[action,setAction]=useState(""),[target,setTarget]=useState(""),[actor,setActor]=useState("");const load=useCallback(async()=>{setLoading(true);setError("");const query=new URLSearchParams();if(action.trim())query.set("action",action.trim().toUpperCase());if(target.trim())query.set("target_type",target.trim().toUpperCase());if(actor.trim())query.set("actor_user_id",actor.trim());query.set("limit","200");try{setItems(await controlService.audit(`?${query}`));}catch(cause){setError(cause instanceof Error?cause.message:"Audit history could not be loaded.");}finally{setLoading(false)}},[action,actor,target]);useEffect(()=>{queueMicrotask(()=>void load())},[]);// eslint-disable-line react-hooks/exhaustive-deps
function filter(event:FormEvent){event.preventDefault();const query=new URLSearchParams();if(action.trim())query.set("action",action.trim());if(target.trim())query.set("target",target.trim());if(actor.trim())query.set("actor",actor.trim());window.history.replaceState(null,"",query.size?`/audit?${query}`:"/audit");void load()}
return <div className="mx-auto max-w-7xl"><p className="eyebrow">Immutable governance history</p><h1 className="page-title">Audit logs</h1><p className="page-subtitle">Trace administrative decisions by action, resource type, actor, rationale, and timestamp. Audit records cannot be edited or deleted here.</p><form onSubmit={filter} className="panel mt-6 grid gap-3 md:grid-cols-[1fr_1fr_180px_auto]"><input className="input" value={action} onChange={event=>setAction(event.target.value)} placeholder="Action, e.g. ROOM_TYPE_REVIEWED" aria-label="Audit action"/><input className="input" value={target} onChange={event=>setTarget(event.target.value)} placeholder="Resource type, e.g. HOTEL" aria-label="Audit resource type"/><input className="input" inputMode="numeric" value={actor} onChange={event=>setActor(event.target.value.replace(/\D/g,""))} placeholder="Actor ID" aria-label="Actor user ID"/><button className="btn-primary">Apply filters</button></form>{error&&<p role="alert" className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</p>}<section className="mt-6 space-y-3">{loading?<div className="panel text-slate-500">Loading audit logs…</div>:items.length===0?<div className="panel empty-state">No audit records match these filters.</div>:items.map(item=><article key={item.id} className="panel"><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="rounded bg-blue-50 px-2 py-1 text-xs font-bold text-blue-700">{item.action.replaceAll("_"," ")}</span><h2 className="mt-3 font-bold">{item.target_type} #{item.target_id}</h2><p className="mt-1 text-sm text-slate-600">{item.reason}</p></div><div className="text-right text-xs text-slate-500"><p>Actor #{item.actor_user_id}</p><time>{new Date(item.created_at).toLocaleString()}</time></div></div><div className="mt-4 grid gap-3 md:grid-cols-2"><Snapshot label="Previous" value={item.previous_value}/><Snapshot label="New" value={item.new_value}/></div></article>)}</section></div>}
function Snapshot({label,value}:{label:string;value:Record<string,unknown>|null}){return <div className="rounded-lg bg-slate-50 p-3"><strong className="text-xs uppercase text-slate-400">{label}</strong><pre className="mt-2 overflow-x-auto whitespace-pre-wrap text-xs text-slate-600">{value?JSON.stringify(value,null,2):"—"}</pre></div>}
