"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { AdminShell } from "@/components/AdminShell";
import { controlService, type AdminUser } from "@/services/control.service";

export default function UsersPage() { return <AdminShell><Users /></AdminShell>; }
function Users() {
  const [items, setItems] = useState<AdminUser[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [role, setRole] = useState(""); const [status, setStatus] = useState(""); const [search, setSearch] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); const params = new URLSearchParams(); if (role) params.set("role", role); if (status) params.set("user_status", status); if (search.trim()) params.set("search", search.trim()); try { setItems(await controlService.users(params.size ? `?${params}` : "")); } catch (cause) { setError(cause instanceof Error ? cause.message : "Users could not be loaded."); } finally { setLoading(false); } }, [role, search, status]);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  async function change(item: AdminUser, next: string) { const reason = window.prompt(`Reason for changing ${item.full_name} to ${next}`); if (!reason || reason.trim().length < 5) return; try { const updated = await controlService.updateUser(item.id, next, reason); setItems((all) => all.map((entry) => entry.id === updated.id ? updated : entry)); } catch (cause) { setError(cause instanceof Error ? cause.message : "User status could not be changed."); } }
  function submit(event: FormEvent) { event.preventDefault(); void load(); }
  return <div className="mx-auto max-w-7xl"><p className="eyebrow">Identity & access</p><h1 className="page-title">Users</h1><p className="page-subtitle">Role-isolated accounts with masked contact details.</p><form onSubmit={submit} className="panel mt-6 grid gap-3 md:grid-cols-[1fr_190px_190px_auto]"><input className="input" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search name or email" /><select className="input" value={role} onChange={(event) => setRole(event.target.value)}><option value="">All roles</option><option>CUSTOMER</option><option>HOTEL_PARTNER</option><option>ADMIN</option></select><select className="input" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">All statuses</option><option>ACTIVE</option><option>INACTIVE</option><option>SUSPENDED</option></select><button className="btn-primary">Filter</button></form>{error && <p role="alert" className="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}<section className="panel mt-6 overflow-x-auto p-0">{loading ? <p className="p-12 text-center text-slate-500">Loading users…</p> : items.length === 0 ? <p className="empty-state m-5">No users match these filters.</p> : <table className="min-w-full text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase text-slate-500"><tr>{["User", "Private contact", "Role", "Status", "Verification", "Action"].map((head) => <th key={head} className="px-4 py-3">{head}</th>)}</tr></thead><tbody className="divide-y">{items.map((item) => <tr key={item.id}><td className="px-4 py-4"><strong>{item.full_name}</strong><span className="block text-xs text-slate-400">ID {item.id}</span></td><td className="px-4 py-4">{item.masked_email}<span className="block text-xs text-slate-400">{item.masked_phone}</span></td><td className="px-4 py-4">{item.role}</td><td className="px-4 py-4"><Badge value={item.status} /></td><td className="px-4 py-4 text-xs">Email {item.is_email_verified ? "✓" : "—"} · Phone {item.is_phone_verified ? "✓" : "—"}</td><td className="px-4 py-4"><select aria-label={`Change status for ${item.full_name}`} className="rounded-lg border p-2 text-xs" value={item.status} onChange={(event) => void change(item, event.target.value)}><option>ACTIVE</option><option>INACTIVE</option><option>SUSPENDED</option></select></td></tr>)}</tbody></table>}</section></div>;
}
function Badge({ value }: { value: string }) { return <span className={`rounded-full px-2.5 py-1 text-xs font-bold ${value === "ACTIVE" ? "bg-emerald-50 text-emerald-700" : value === "SUSPENDED" ? "bg-red-50 text-red-700" : "bg-slate-100 text-slate-600"}`}>{value}</span>; }
