import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Advertise on Maharashtra Tourist Places",
  description: "Reach travellers through clearly labelled, reviewed sponsored placements on Maharashtra Tourist Places.",
};

export default function AdvertisePage() {
  return <main>
    <section className="bg-[var(--brand)] py-20 text-white"><div className="container-shell max-w-5xl"><p className="text-sm font-black uppercase tracking-[.18em] text-orange-300">Maharashtra Tourist Places advertising</p><h1 className="mt-4 max-w-3xl text-4xl font-black leading-tight sm:text-6xl">Reach travellers with reviewed, clearly labelled advertising.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-200">Hotels already on Maharashtra Tourist Places and legitimate independent businesses can request Homepage or Destination placements using Maharashtra Tourist Places&apos; existing campaign plans.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/register?next=/advertiser" className="rounded-xl bg-orange-500 px-6 py-3 font-black text-white hover:bg-orange-400">Start advertising</Link><Link href="/login?next=/advertiser" className="rounded-xl border border-white/40 px-6 py-3 font-black text-white hover:bg-white/10">Sign in</Link></div></div></section>
    <section className="container-shell py-16"><div className="grid gap-6 md:grid-cols-3"><article className="rounded-2xl border bg-white p-6"><p className="text-xs font-black uppercase tracking-widest text-orange-600">01</p><h2 className="mt-3 text-xl font-black">Create your campaign</h2><p className="mt-2 text-slate-600">Choose an available plan, provide customer-facing copy, a public HTTPS destination, and a creative you are authorized to use.</p></article><article className="rounded-2xl border bg-white p-6"><p className="text-xs font-black uppercase tracking-widest text-orange-600">02</p><h2 className="mt-3 text-xl font-black">Pay securely</h2><p className="mt-2 text-slate-600">Pricing is determined by Maharashtra Tourist Places&apos; server-side plan configuration. Payment confirms payment only—it does not approve or publish an advertisement.</p></article><article className="rounded-2xl border bg-white p-6"><p className="text-xs font-black uppercase tracking-widest text-orange-600">03</p><h2 className="mt-3 text-xl font-black">Maharashtra Tourist Places reviews</h2><p className="mt-2 text-slate-600">Every campaign is reviewed before scheduling. Approved placements remain visibly marked Sponsored and may be paused for policy or safety reasons.</p></article></div><div className="mt-10 rounded-2xl bg-amber-50 p-6 text-amber-950"><h2 className="font-black">Advertising standards</h2><p className="mt-2 max-w-4xl">Misleading, unsafe, prohibited, rights-infringing, or unverifiable advertisements are not accepted. Material changes to approved copy, creative, or destinations require another review. Rejection of a paid campaign is handled through Maharashtra Tourist Places&apos; operational refund review; no automatic refund promise is made here.</p></div></section>
  </main>;
}
