"use client";

import { useCallback, useEffect, useState } from "react";

import { AdminShell } from "@/components/AdminShell";
import { AdminReview, reviewService } from "@/services/review.service";

export default function ReviewsPage() { return <AdminShell><ModerationQueue /></AdminShell>; }

function ModerationQueue() {
  const [items, setItems] = useState<AdminReview[]>([]); const [selected, setSelected] = useState<AdminReview | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async () => { setError(""); try { const data = await reviewService.queue(); setItems(data); setSelected((current) => current ? data.find((item) => item.id === current.id) ?? null : null); } catch (cause) { setError(cause instanceof Error ? cause.message : "Moderation queue could not be loaded."); } finally { setLoading(false); } }, []);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  async function decide(action: "PUBLISH" | "REJECT", note: string) { if (!selected) return; setBusy(true); setError(""); try { await reviewService.moderate(selected.id, action, note); setSelected(null); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Moderation decision failed."); } finally { setBusy(false); } }
  return <div className="mx-auto max-w-7xl"><p className="text-sm font-semibold uppercase tracking-[.16em] text-indigo-700">Trust & safety</p><h1 className="mt-1 text-3xl font-bold">Review moderation</h1><p className="mt-2 text-sm text-slate-500">High-risk content and hotel challenges appear here. Low ratings alone are not moderation signals.</p>{error && <p role="alert" className="mt-5 rounded-xl bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</p>}<div className="mt-7 grid gap-6 lg:grid-cols-[1fr_1fr]"><section className="overflow-hidden rounded-2xl border bg-white shadow-sm">{loading ? <p className="p-12 text-center text-slate-400">Loading moderation queue…</p> : items.length === 0 ? <p className="p-12 text-center text-slate-400">No reviews need moderation.</p> : <div className="divide-y">{items.map((item) => <button key={item.id} onClick={() => setSelected(item)} className="w-full p-5 text-left hover:bg-slate-50"><span className="flex justify-between gap-4"><strong>{item.hotel.name}</strong><span className={`rounded-full px-2 py-1 text-xs font-bold ${item.risk_level === "HIGH" ? "bg-red-50 text-red-700" : "bg-amber-50 text-amber-700"}`}>{item.risk_level === "HIGH" ? "HIGH RISK" : "CHALLENGED"}</span></span><span className="mt-1 block text-xs text-slate-500">{item.booking.booking_reference} · {item.overall_rating}/5</span><span className="mt-2 line-clamp-2 block text-sm text-slate-600">{item.review_text}</span></button>)}</div>}</section><section className="panel">{selected ? <ModerationDetail review={selected} busy={busy} onDecide={decide} /> : <p className="py-16 text-center text-sm text-slate-400">Select an escalated review.</p>}</section></div></div>;
}

function ModerationDetail({ review, busy, onDecide }: { review: AdminReview; busy: boolean; onDecide: (action: "PUBLISH" | "REJECT", note: string) => Promise<void> }) {
  const [note, setNote] = useState(""); return <><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-700">✓ Verified Stay</span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold">{review.moderation_status.replaceAll("_", " ")}</span></div><h2 className="mt-5 text-xl font-bold">{review.hotel.name}</h2><p className="mt-1 text-xs text-slate-500">{review.booking.booking_reference}</p><p className="mt-5 whitespace-pre-wrap leading-7 text-slate-700">{review.review_text}</p>{review.risk_reasons.length > 0 && <div className="mt-5 rounded-xl bg-red-50 p-4 text-sm text-red-800"><strong>Automated escalation signals</strong><p className="mt-1">{review.risk_reasons.map((item) => item.replaceAll("_", " ")).join(", ")}</p></div>}{review.challenge && <div className="mt-5 rounded-xl bg-amber-50 p-4 text-sm text-amber-800"><strong>Hotel challenge: {review.challenge.reason.replaceAll("_", " ")}</strong><p className="mt-2">{review.challenge.details}</p></div>}<label className="mt-6 block text-sm font-bold">Decision rationale<textarea className="input mt-2" required minLength={3} maxLength={3000} rows={5} value={note} onChange={(event) => setNote(event.target.value)} /></label><div className="mt-4 flex gap-3"><button disabled={busy || note.trim().length < 3} className="btn-primary" onClick={() => void onDecide("PUBLISH", note)}>Publish / retain</button><button disabled={busy || note.trim().length < 3} className="btn-secondary !border-red-200 !text-red-700" onClick={() => void onDecide("REJECT", note)}>Reject review</button></div><h3 className="mt-7 border-t pt-5 font-bold">Audit history</h3><ol className="mt-3 space-y-3">{review.moderation_events.map((event) => <li key={event.id} className="border-l-2 border-slate-200 pl-3 text-xs"><strong>{event.new_status.replaceAll("_", " ")}</strong><p className="mt-1 text-slate-500">{event.note}</p></li>)}</ol></>;
}
