"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";

import { DiscoveryMediaManager, DiscoveryMediaUpload, DiscoveryPreview, FAQEditor, LifecycleActions } from "@/components/DiscoveryEditorTools";
import { FormError } from "@/components/FormError";
import { StatusBadge } from "@/components/StatusBadge";
import { ApiError } from "@/services/api";
import { discoveryService } from "@/services/discovery.service";
import type { AdminDestination, AdminPlace, DiscoveryFAQ, DiscoveryReference, PlaceInput, SpiritualTradition } from "@/types/discovery";

export function PlaceEditor({ id }: { id?: number }) {
  const router = useRouter(); const [reference, setReference] = useState<DiscoveryReference | null>(null); const [item, setItem] = useState<AdminPlace | null>(null); const [destinations, setDestinations] = useState<AdminDestination[]>([]);
  const [districtId, setDistrictId] = useState(0); const [destinationId, setDestinationId] = useState<number | null>(null); const [selectedInterests, setSelectedInterests] = useState<number[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const [faqs, setFaqs] = useState<DiscoveryFAQ[]>([]);
  const sacredId = useMemo(() => reference?.interests.find((value) => value.slug === "sacred-spiritual")?.id, [reference]);
  async function load() { setLoading(true); setError(""); try { const [ref, entity] = await Promise.all([discoveryService.reference(), id ? discoveryService.place(id) : Promise.resolve(null)]); setReference(ref); setItem(entity); setFaqs(entity?.faqs ?? []); const nextDistrict = entity?.district_id ?? ref.districts[0]?.id ?? 0; setDistrictId(nextDistrict); setDestinationId(entity?.destination_id ?? null); setSelectedInterests(entity?.interests.map((value) => value.id) ?? []); setDestinations(nextDistrict ? await discoveryService.destinationsForDistrict(nextDistrict) : []); } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Unable to load place."); } finally { setLoading(false); } }
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
  useEffect(() => { void load(); }, [id]);
  async function changeDistrict(value: number) { setDistrictId(value); setDestinationId(null); setDestinations(await discoveryService.destinationsForDistrict(value)); }
  function toggleInterest(value: number) { setSelectedInterests((current) => current.includes(value) ? current.filter((idValue) => idValue !== value) : [...current, value]); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const spiritualValue = form.get("spiritual_tradition"); const spiritual = typeof spiritualValue === "string" ? spiritualValue : ""; const text = (name: string) => String(form.get(name) ?? "").trim() || null; const body: PlaceInput = {district_id: districtId, destination_id: destinationId, name: String(form.get("name")).trim(), short_description: text("short_description"), description: text("description"), interest_ids: selectedInterests, spiritual_tradition: spiritual ? spiritual as SpiritualTradition : null, is_featured: form.get("is_featured") === "on", display_order: Number(form.get("display_order")), address: text("address"), opening_hours: text("opening_hours"), entry_fee_info: text("entry_fee_info"), recommended_visit_duration: text("recommended_visit_duration"), best_time_to_visit: text("best_time_to_visit"), getting_there: text("getting_there"), nearest_railway_station: text("nearest_railway_station"), nearest_airport: text("nearest_airport"), visitor_info_source: text("visitor_info_source"), visitor_info_source_url: text("visitor_info_source_url"), visitor_info_verified_at: text("visitor_info_verified_at"), faqs: faqs.map((faq, index) => ({...faq, question: faq.question.trim(), answer: faq.answer.trim(), display_order: index}))}; setSaving(true); setError(""); try { if (item) setItem(await discoveryService.updatePlace(item.id, {...body, expected_version: item.version})); else { const created = await discoveryService.createPlace(body); router.replace(`/discovery/places/${created.id}`); } } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Unable to save place."); } finally { setSaving(false); } }
  if (loading) return <div className="panel">Loading place…</div>;
  const hasSacred = sacredId ? selectedInterests.includes(sacredId) : false;
  return <div className="mx-auto max-w-6xl"><div className="mb-7 flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">Discovery management</p><div className="flex items-center gap-3"><h1 className="page-title">{item ? item.name : "New place"}</h1>{item && <StatusBadge status={item.status} />}</div><p className="page-subtitle">Classify a real Maharashtra place using the canonical district and interest taxonomy.</p></div>{item && <LifecycleActions kind="places" entity={item} onChange={(value) => setItem(value as AdminPlace)} />}</div><FormError message={error} />
    <div className="mt-5 grid gap-6 lg:grid-cols-[1.15fr_.85fr]"><div className="space-y-6"><form onSubmit={submit} className="panel space-y-5"><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Canonical district<select required value={districtId} onChange={(event) => void changeDistrict(Number(event.target.value))} name="district_id" className="input mt-2">{reference?.districts.map((value) => <option value={value.id} key={value.id}>{value.name}</option>)}</select></label><label className="text-sm font-bold">Destination (optional)<select value={destinationId ?? ""} onChange={(event) => setDestinationId(event.target.value ? Number(event.target.value) : null)} name="destination_id" className="input mt-2"><option value="">District only</option>{destinations.map((value) => <option value={value.id} key={value.id}>{value.name} · {value.status}</option>)}</select></label></div><label className="block text-sm font-bold">Name<input required minLength={2} maxLength={160} defaultValue={item?.name} name="name" className="input mt-2" /></label><label className="block text-sm font-bold">Short description<textarea required rows={3} maxLength={500} defaultValue={item?.short_description ?? ""} name="short_description" className="input mt-2" /></label><label className="block text-sm font-bold">Full description<textarea required rows={10} defaultValue={item?.description ?? ""} name="description" className="input mt-2" /></label>
      <fieldset className="space-y-4 rounded-xl border border-slate-200 p-4"><legend className="px-2 text-sm font-black">Visitor information</legend><label className="block text-sm font-bold">Address or location<input name="address" maxLength={500} defaultValue={item?.address ?? ""} className="input mt-2" /></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Opening hours<textarea name="opening_hours" rows={3} defaultValue={item?.opening_hours ?? ""} className="input mt-2" /></label><label className="text-sm font-bold">Entry fee information<textarea name="entry_fee_info" rows={3} defaultValue={item?.entry_fee_info ?? ""} className="input mt-2" /></label><label className="text-sm font-bold">Recommended visit duration<input name="recommended_visit_duration" maxLength={120} defaultValue={item?.recommended_visit_duration ?? ""} className="input mt-2" /></label><label className="text-sm font-bold">Best time to visit<input name="best_time_to_visit" maxLength={300} defaultValue={item?.best_time_to_visit ?? ""} className="input mt-2" /></label></div></fieldset>
      <fieldset className="space-y-4 rounded-xl border border-slate-200 p-4"><legend className="px-2 text-sm font-black">Getting there</legend><label className="block text-sm font-bold">Road and general transport guidance<textarea name="getting_there" rows={5} defaultValue={item?.getting_there ?? ""} className="input mt-2" /></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Nearest railway station<input name="nearest_railway_station" defaultValue={item?.nearest_railway_station ?? ""} className="input mt-2" /></label><label className="text-sm font-bold">Nearest airport<input name="nearest_airport" defaultValue={item?.nearest_airport ?? ""} className="input mt-2" /></label></div></fieldset>
      <fieldset className="space-y-4 rounded-xl border border-slate-200 p-4"><legend className="px-2 text-sm font-black">Verification</legend><p className="text-sm text-slate-500">Use these fields for information that may change. Maharashtra Tourist Places does not automatically claim it is current.</p><label className="block text-sm font-bold">Source or reference<input name="visitor_info_source" maxLength={500} defaultValue={item?.visitor_info_source ?? ""} className="input mt-2" /></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Source URL<input name="visitor_info_source_url" type="url" defaultValue={item?.visitor_info_source_url ?? ""} className="input mt-2" /></label><label className="text-sm font-bold">Last verified<input name="visitor_info_verified_at" type="date" max={new Date().toISOString().slice(0,10)} defaultValue={item?.visitor_info_verified_at ?? ""} className="input mt-2" /></label></div></fieldset>
      <fieldset><legend className="text-sm font-bold">Interests</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{reference?.interests.map((value) => <label key={value.id} className="flex gap-2 rounded-lg border border-slate-200 p-3 text-sm"><input type="checkbox" checked={selectedInterests.includes(value.id)} onChange={() => toggleInterest(value.id)} />{value.name}</label>)}</div></fieldset>
      {hasSacred && <label className="block text-sm font-bold">Spiritual tradition<select name="spiritual_tradition" defaultValue={item?.spiritual_tradition ?? ""} className="input mt-2"><option value="">Not classified</option>{reference?.spiritual_traditions.map((value) => <option key={value}>{value.replaceAll("_", " ")}</option>)}</select></label>}
      <div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Display order<input name="display_order" type="number" min={0} defaultValue={item?.display_order ?? 0} className="input mt-2" /></label><label className="mt-7 flex items-center gap-2 text-sm font-bold"><input name="is_featured" type="checkbox" defaultChecked={item?.is_featured} />Featured place</label></div>{item && <p className="text-xs text-slate-500">Stable slug: <strong>{item.slug}</strong> · Source: {item.content_source}{item.admin_overridden ? " · protected from curated seed resets" : ""}</p>}<button disabled={saving || faqs.some((faq) => !faq.question.trim() || !faq.answer.trim())} className="btn-primary">{saving ? "Saving…" : item ? "Save content and FAQs" : "Create draft"}</button></form><FAQEditor value={faqs} onChange={setFaqs} />{item && <><DiscoveryMediaUpload entityType="PLACE" entityId={item.id} onUploaded={load} /><DiscoveryMediaManager entityType="PLACE" entity={item} onChange={(value) => setItem(value as AdminPlace)} /></>}</div>{item ? <DiscoveryPreview entity={item} /> : <aside className="panel text-sm text-slate-600"><h2 className="font-black text-slate-950">Publication checks</h2><p className="mt-2">A place needs descriptions and at least one interest before it can be published. Destination links are validated against the selected district.</p></aside>}</div>
  </div>;
}
