"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";

import { partnerService } from "@/src/services/partner.service";
import type { PartnerReview, ReviewChallengeReason } from "@/src/types/partner";

const reasons: Array<[ReviewChallengeReason, string]> = [["FAKE_OR_MISLEADING", "Fake or misleading"], ["WRONG_PROPERTY", "Wrong property"], ["SPAM", "Spam"], ["ABUSIVE_CONTENT", "Abusive content"], ["PERSONAL_INFORMATION", "Personal information"], ["EXTORTION", "Extortion"], ["MANIPULATION", "Manipulation"], ["OTHER_POLICY_VIOLATION", "Other policy violation"]];

export default function PartnerReviewsPage() {
  const [items, setItems] = useState<PartnerReview[]>([]); const [selected, setSelected] = useState<PartnerReview | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setError(""); try { const data = await partnerService.getReviews(); setItems(data); setSelected((current) => current ? data.find((item) => item.id === current.id) ?? null : null); } catch (cause) { setError(cause instanceof Error ? cause.message : "Guest reviews could not be loaded."); } finally { setLoading(false); } }, []);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  return <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><Link href="/partner/dashboard" className="text-sm font-black text-[#172554]">← Partner dashboard</Link><p className="mt-6 text-xs font-black uppercase tracking-[.16em] text-[#d95025]">Reputation</p><h1 className="mt-2 text-3xl font-black text-[#0b163d]">Guest reviews</h1><p className="mt-2 text-sm text-slate-500">Respond publicly or challenge a review without altering the guest’s words or ratings.</p>{error && <p role="alert" className="mt-5 rounded-xl bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</p>}<div className="mt-7 grid gap-6 lg:grid-cols-[1fr_1fr]"><section className="rounded-2xl border bg-white shadow-sm">{loading ? <p className="p-12 text-center text-slate-400">Loading reviews…</p> : items.length === 0 ? <p className="p-12 text-center text-slate-400">No verified-stay reviews yet.</p> : <div className="divide-y">{items.map((item) => <button className="w-full p-5 text-left hover:bg-slate-50" key={item.id} onClick={() => setSelected(item)}><span className="flex justify-between gap-4"><strong>{item.overall_rating} / 5 · {item.booking.booking_reference}</strong><span className="text-xs font-black text-slate-500">{item.moderation_status.replaceAll("_", " ")}</span></span><span className="mt-2 line-clamp-2 block text-sm text-slate-500">{item.review_text}</span></button>)}</div>}</section><section className="rounded-2xl border bg-white p-6 shadow-sm">{selected ? <ReviewActions key={selected.id} review={selected} onUpdated={(updated) => { setSelected(updated); void load(); }} /> : <p className="py-16 text-center text-sm text-slate-400">Select a review to respond or challenge it.</p>}</section></div></main>;
}

function ReviewActions({ review, onUpdated }: { review: PartnerReview; onUpdated: (review: PartnerReview) => void }) {
  const [response, setResponse] = useState(""); const [reason, setReason] = useState<ReviewChallengeReason>("FAKE_OR_MISLEADING"); const [details, setDetails] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function run(action: () => Promise<PartnerReview>) { setBusy(true); setError(""); try { onUpdated(await action()); } catch (cause) { setError(cause instanceof Error ? cause.message : "Review action failed."); } finally { setBusy(false); } }
  function respond(event: FormEvent) { event.preventDefault(); void run(() => partnerService.respondToReview(review.id, response)); }
  function challenge(event: FormEvent) { event.preventDefault(); void run(() => partnerService.challengeReview(review.id, reason, details)); }
  return <><div className="flex flex-wrap items-center gap-2"><span className="status-pill bg-emerald-50 text-emerald-700">✓ Verified Stay</span><span className="status-pill bg-amber-50 text-amber-700">{review.overall_rating} ★</span></div><p className="mt-5 whitespace-pre-wrap leading-7 text-slate-700">{review.review_text}</p><dl className="mt-5 grid grid-cols-2 gap-3 text-xs text-slate-500"><dt>Cleanliness: {review.cleanliness_rating}/5</dt><dt>Staff/service: {review.service_rating}/5</dt><dt>Location: {review.location_rating}/5</dt><dt>Room quality: {review.room_quality_rating}/5</dt><dt>Value: {review.value_rating}/5</dt></dl>{error && <p className="mt-4 text-sm font-semibold text-red-700">{error}</p>}{review.hotel_response ? <div className="mt-6 rounded-xl bg-slate-50 p-4 text-sm"><strong>Your public response</strong><p className="mt-2 text-slate-600">{review.hotel_response.response_text}</p></div> : review.moderation_status === "PUBLISHED" && <form onSubmit={respond} className="mt-6 border-t pt-5"><label className="text-sm font-black">Public hotel response<textarea required minLength={3} maxLength={3000} rows={4} className="field-input mt-2" value={response} onChange={(event) => setResponse(event.target.value)} /></label><button disabled={busy || response.trim().length < 3} className="primary-button mt-3">Publish response</button></form>}{review.challenge ? <div className="mt-6 rounded-xl bg-amber-50 p-4 text-sm text-amber-800"><strong>Challenge {review.challenge.status.toLowerCase()}</strong><p className="mt-1">{review.challenge.reason.replaceAll("_", " ")}: {review.challenge.details}</p>{review.challenge.resolution_note && <p className="mt-2">Admin: {review.challenge.resolution_note}</p>}</div> : <form onSubmit={challenge} className="mt-6 border-t pt-5"><label className="text-sm font-black">Challenge reason<select className="field-input mt-2" value={reason} onChange={(event) => setReason(event.target.value as ReviewChallengeReason)}>{reasons.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="mt-3 block text-sm font-black">Evidence and details<textarea required minLength={10} maxLength={3000} rows={4} className="field-input mt-2" value={details} onChange={(event) => setDetails(event.target.value)} /></label><button disabled={busy || details.trim().length < 10} className="secondary-button mt-3">Submit challenge</button></form>}</>;
}
