import { authorizedApi } from "@/services/authorized-api";
export type SafariStatus = "AVAILABILITY_REQUESTED" | "CHECKING_AVAILABILITY" | "AWAITING_TRAVELLER_DETAILS" | "DETAILS_SUBMITTED" | "PAYMENT_PENDING" | "BOOKING_IN_PROGRESS" | "CONFIRMED" | "NOT_AVAILABLE" | "EXPIRED" | "CANCELLED" | "BOOKING_FAILED";
export interface SafariRequest { id: number; request_reference: string; safari: { id: number; name: string; booking_categories: Array<{ code?: string; label?: string }>; vehicle_options: Array<{ code?: string; label?: string }>; official_reference_required: boolean; official_contact_required: boolean; official_document_required: boolean; source_url?: string; last_verified_at?: string; traveller_requirements: Record<string, unknown> }; preferred_date: string; preferred_shift?: string; preferred_booking_category?: string; preferred_vehicle_option?: string; visitor_count: number; status: SafariStatus; availability_result?: string; target_response_at: string; responded_at?: string; overdue: boolean; payable_amount?: string; currency?: string; price_breakdown?: Record<string, unknown>; payment_status: string; payment_reconciliation_status?: string; refund_status?: string; travellers: Array<{ id: number; position: number; details: Record<string, unknown> }>; confirmation_documents: Array<{ id: number; document_type: string; original_name: string }>; external_booking_reference?: string; confirmed_booking_category?: string; confirmed_vehicle_option?: string; official_booking_contact_masked?: string; operator_confirmed_at?: string; failure_reason?: string }
export interface SafariNotice { id: number; safari_id?: number; title: string; body: string; severity: "INFO" | "WARNING" | "RESTRICTION"; effective_from?: string; effective_until?: string; is_active: boolean; source_url?: string; last_verified_at?: string }
export const safariService = {
  list: (status?: SafariStatus, overdue = false) => { const query = new URLSearchParams(); if (status) query.set("status", status); if (overdue) query.set("overdue", "true"); return authorizedApi.get<SafariRequest[]>(`/admin/safari-operations?${query}`); },
  availability: (id: number, action: string, reason: string, alternatives: Array<Record<string, unknown>> = []) => authorizedApi.post<SafariRequest, Record<string, unknown>>(`/admin/safari-operations/${id}/availability`, { action, reason, alternatives }),
  pricing: (id: number, amount: string, currency: string, breakdown: Record<string, unknown>, reason: string) => authorizedApi.post<SafariRequest, Record<string, unknown>>(`/admin/safari-operations/${id}/pricing`, { amount, currency, breakdown, reason }),
  confirm: (id: number, body: Record<string, unknown>) => authorizedApi.post<SafariRequest, Record<string, unknown>>(`/admin/safari-operations/${id}/confirm`, body),
  uploadConfirmation: (id: number, file: File, documentType: string) => { const body = new FormData(); body.set("file", file); body.set("document_type", documentType); return authorizedApi.post<Record<string, unknown>, FormData>(`/admin/safari-operations/${id}/confirmation-documents`, body); },
  configure: (id: number, body: Record<string, unknown>) => authorizedApi.patch<Record<string, unknown>, Record<string, unknown>>(`/admin/safaris/${id}/configuration`, body),
  notices: () => authorizedApi.get<SafariNotice[]>("/admin/safari-notices"),
  createNotice: (body: Record<string, unknown>) => authorizedApi.post<SafariNotice, Record<string, unknown>>("/admin/safari-notices", body),
  updateNotice: (id: number, body: Record<string, unknown>) => authorizedApi.patch<SafariNotice, Record<string, unknown>>(`/admin/safari-notices/${id}`, body),
  fail: (id: number, reason: string) => authorizedApi.post<SafariRequest, { reason: string }>(`/admin/safari-operations/${id}/fail`, { reason }),
};
