"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

import { useAuth } from "@/src/context/AuthContext";
import { isCustomerRole } from "@/src/lib/portal-routing";
import { safariStatusClasses, safariStatusDisplay } from "@/src/lib/safari-status";
import { safariService } from "@/src/services/safari.service";
import { openPaymentCheckout } from "@/src/lib/payment-checkout";
import type { SafariRequest, SafariTraveller } from "@/src/types/safari";

type Filter = "ALL" | "ACTION" | "ACTIVE" | "CLOSED";
const PRIVATE_DOCUMENT_MAX_BYTES = 10 * 1024 * 1024;
const closedStatuses = new Set(["CONFIRMED", "NOT_AVAILABLE", "EXPIRED", "CANCELLED", "BOOKING_FAILED"]);

function needsAction(item: SafariRequest) { return item.status === "AWAITING_TRAVELLER_DETAILS" || item.status === "PAYMENT_PENDING" || (item.status === "NOT_AVAILABLE" && item.alternatives.length > 0); }
function isClosed(item: SafariRequest) { return closedStatuses.has(item.status); }

export function SafariAccount() {
  const { loading: authLoading, user } = useAuth();
  const [items, setItems] = useState<SafariRequest[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [filter, setFilter] = useState<Filter>("ALL");
  const customer = user && isCustomerRole(user.role);

  const load = useCallback(async (silent = false) => {
    if (!silent) setLoading(true); setError("");
    try { setItems(await safariService.mine()); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Safari requests could not be loaded."); }
    finally { if (!silent) setLoading(false); }
  }, []);

  useEffect(() => { if (!authLoading && customer) queueMicrotask(() => { void load(); }); }, [authLoading, customer, load]);
  useEffect(() => {
    if (!customer || !items.some((item) => !isClosed(item))) return;
    const timer = window.setInterval(() => { void load(true); }, 30_000);
    return () => window.clearInterval(timer);
  }, [customer, items, load]);

  const visible = useMemo(() => items.filter((item) => filter === "ALL" || (filter === "ACTION" && needsAction(item)) || (filter === "ACTIVE" && !isClosed(item)) || (filter === "CLOSED" && isClosed(item))), [filter, items]);
  function update(updated: SafariRequest, message?: string) { setItems((current) => current.map((item) => item.id === updated.id ? updated : item)); if (message) setNotice(message); }

  if (authLoading) return <AccountShell><LoadingCards /></AccountShell>;
  if (!customer) return <AccountShell><div className="content-card text-center"><h2 className="text-xl font-black text-[var(--brand)]">Customer sign-in required</h2><p className="mt-2 text-sm text-slate-600">Sign in to view safari requests and secure documents associated with your account.</p><Link href="/login" className="primary-button mt-5">Sign in</Link></div></AccountShell>;
  return <AccountShell>
    {notice && <div role="status" className="mb-5 flex items-start justify-between gap-4 rounded-xl border border-blue-100 bg-blue-50 p-4 text-sm font-semibold text-blue-800"><span>{notice}</span><button type="button" onClick={() => setNotice("")} aria-label="Dismiss message">×</button></div>}
    {error && <div role="alert" className="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><p className="font-bold">{error}</p><button type="button" onClick={() => void load()} className="mt-3 font-black underline">Try again</button></div>}
    {loading ? <LoadingCards /> : items.length ? <><div className="mb-6 flex flex-wrap gap-2" aria-label="Filter safari requests">{(["ALL", "ACTION", "ACTIVE", "CLOSED"] as Filter[]).map((value) => <button type="button" key={value} onClick={() => setFilter(value)} aria-pressed={filter === value} className={`rounded-full border px-4 py-2 text-xs font-black ${filter === value ? "border-[var(--accent)] bg-[var(--accent-soft)] text-[var(--accent-strong)]" : "border-[var(--line)] bg-white text-slate-600"}`}>{value === "ALL" ? "All" : value === "ACTION" ? "Action needed" : value === "ACTIVE" ? "In progress" : "Closed"}</button>)}</div><div className="space-y-6">{visible.map((item) => <SafariRequestCard key={item.id} item={item} onUpdate={update} onNotice={setNotice} compact />)}{!visible.length && <p className="content-card text-center text-sm text-slate-500">No requests match this filter.</p>}</div></> : <div className="content-card text-center"><h2 className="text-xl font-black text-[var(--brand)]">No safari requests yet</h2><p className="mt-2 text-sm text-slate-500">Explore the supported catalogue and send a managed availability request.</p><Link href="/safaris" className="primary-button mt-5">Explore safaris</Link></div>}
  </AccountShell>;
}

function AccountShell({ children }: { children: React.ReactNode }) { return <div><div className="mb-8 flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">Your account</p><h1 className="page-title mt-2">Safari requests</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">Track availability, complete requested steps, and access confirmed booking documents securely.</p></div><Link href="/safaris" className="secondary-button">Explore safaris</Link></div>{children}</div>; }
function LoadingCards() { return <div className="space-y-5" aria-label="Loading safari requests">{[1, 2].map((item) => <div key={item} className="h-64 animate-pulse rounded-2xl border border-[var(--line)] bg-white p-6"><div className="h-6 w-52 rounded bg-slate-100" /><div className="mt-4 h-16 rounded bg-slate-100" /></div>)}</div>; }

export function SafariRequestCard({ item, onUpdate, onNotice, compact = false }: { item: SafariRequest; onUpdate: (item: SafariRequest, message?: string) => void; onNotice: (message: string) => void; compact?: boolean }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const display = safariStatusDisplay(item.status);
  const hotelHref = item.safari.hotel_destination_filter ? `/hotels?destination=${encodeURIComponent(item.safari.hotel_destination_filter)}&city=${encodeURIComponent(item.safari.destination_name || item.safari.district_name || item.safari.name)}` : undefined;
  if (compact) return <article className="rounded-2xl border border-[var(--line)] bg-white p-6 shadow-[var(--shadow-sm)]"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.14em] text-[var(--accent-strong)]">{item.request_reference}</p><h2 className="mt-2 text-xl font-black text-[var(--brand-strong)]">{item.safari.name}</h2><p className="mt-2 text-sm text-slate-500">{formatDate(item.preferred_date)} · {item.visitor_count} visitor{item.visitor_count === 1 ? "" : "s"}{item.preferred_shift ? ` · ${item.preferred_shift}` : ""}</p></div><span className={`rounded-full border px-3 py-1.5 text-xs font-black ${safariStatusClasses(display.tone)}`}>{display.label}</span></div><div className="mt-5 flex flex-wrap items-center justify-between gap-4 border-t border-[var(--line)] pt-5"><p className="text-sm text-slate-600"><b className="text-[var(--brand)]">Next:</b> {display.nextAction}</p><Link href={`/account/safaris/${item.request_reference}`} className={needsAction(item) ? "primary-button !min-h-10" : "secondary-button !min-h-10"}>{item.status === "CONFIRMED" ? "View booking / permit" : item.status === "NOT_AVAILABLE" && item.alternatives.length ? "View alternatives" : needsAction(item) ? display.nextAction : "View request"}</Link></div></article>;
  async function action(run: () => Promise<SafariRequest>, success: string) { setBusy(true); setError(""); try { onUpdate(await run(), success); } catch (cause) { setError(cause instanceof Error ? cause.message : "The action could not be completed."); } finally { setBusy(false); } }
  async function download(documentId: number, filename: string) { setBusy(true); setError(""); try { await safariService.download(item.id, documentId, filename); } catch (cause) { setError(cause instanceof Error ? cause.message : "The document could not be downloaded."); } finally { setBusy(false); } }

  return <article className="overflow-hidden rounded-2xl border border-[var(--line)] bg-white shadow-[var(--shadow-sm)]"><div className="p-6 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.14em] text-[var(--accent-strong)]">{item.request_reference}</p><h2 className="mt-2 text-2xl font-black text-[var(--brand-strong)]">{item.safari.name}</h2><p className="mt-2 text-sm text-slate-500">Requested {formatDate(item.preferred_date)} · {item.visitor_count} visitor{item.visitor_count === 1 ? "" : "s"}{item.preferred_shift ? ` · ${item.preferred_shift}` : ""}{item.preferred_booking_category ? ` · ${pretty(item.preferred_booking_category)}` : ""}{item.preferred_vehicle_option ? ` · ${pretty(item.preferred_vehicle_option)}` : ""}</p></div><span className={`rounded-full border px-3 py-1.5 text-xs font-black ${safariStatusClasses(display.tone)}`}>{display.label}</span></div>
        <div className={`mt-5 rounded-xl border p-4 ${safariStatusClasses(display.tone)}`}><p className="text-sm font-semibold leading-6">{display.description}</p><p className="mt-1 text-xs font-black">Next: {display.nextAction}</p></div>
        {item.safari.operational_notices.length > 0 && <OperationalNotices item={item} />}
        {(item.status === "AVAILABILITY_REQUESTED" || item.status === "CHECKING_AVAILABILITY") && <ResponseTarget item={item} />}
        {item.status === "NOT_AVAILABLE" && <Alternatives item={item} busy={busy} onSelect={(id) => void action(() => safariService.alternative(item.id, id), "Alternative selected. Traveller requirements are now available.")} />}
        {item.status === "AWAITING_TRAVELLER_DETAILS" && <AvailabilityFound item={item} />}
        {item.status === "AWAITING_TRAVELLER_DETAILS" && <TravellerRequirements item={item} busy={busy} setBusy={setBusy} onUpdate={onUpdate} setError={setError} />}
        {(item.status === "DETAILS_SUBMITTED" || item.status === "PAYMENT_PENDING" || item.status === "BOOKING_IN_PROGRESS" || item.status === "CONFIRMED" || item.status === "BOOKING_FAILED") && <PriceReview item={item} />}
        {item.status === "PAYMENT_PENDING" && <PaymentPanel item={item} busy={busy} onCreate={() => void createPayment()} />}
        {item.status === "BOOKING_IN_PROGRESS" && <div className="mt-5 rounded-xl border border-blue-100 bg-blue-50 p-5"><p className="font-black text-blue-900">Payment received · booking being processed</p><p className="mt-2 text-sm leading-6 text-blue-800">Maharashtra Tourist Places operations is completing the reservation externally. Payment does not by itself confirm the safari.</p></div>}
        {item.status === "CONFIRMED" && <Confirmation item={item} busy={busy} hotelHref={hotelHref} onDownload={(id, name) => void download(id, name)} />}
        {item.status === "BOOKING_FAILED" && <FailurePanel item={item} />}
        {error && <p role="alert" className="mt-5 rounded-xl border border-red-100 bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p>}
        <div className="mt-6 flex flex-wrap gap-3 border-t border-[var(--line)] pt-5"><Link href={`/safaris/${item.safari.slug}`} className="text-sm font-black text-[var(--accent)] hover:text-[var(--accent-strong)]">Safari details</Link>{item.safari.destination_path && <Link href={item.safari.destination_path} className="text-sm font-black text-[var(--accent)] hover:text-[var(--accent-strong)]">Destination</Link>}{hotelHref && item.status !== "CONFIRMED" && <Link href={hotelHref} className="text-sm font-black text-[var(--accent)] hover:text-[var(--accent-strong)]">Find stays nearby</Link>}</div>
      </div></article>;

  async function createPayment() {
    setBusy(true); setError("");
    try {
      const order = await safariService.payment(item.id);
      if (order.provider === "RAZORPAY") await openPaymentCheckout(order, `Safari request ${item.request_reference}`);
      onNotice("Payment evidence is being verified. Safari confirmation remains a separate Maharashtra Tourist Places operations step.");
      onUpdate(await safariService.getRequest(item.id));
    }
    catch (cause) { setError(cause instanceof Error ? cause.message : "A payment session could not be created."); }
    finally { setBusy(false); }
  }
}

function ResponseTarget({ item }: { item: SafariRequest }) { return <div className="mt-5 flex flex-wrap items-center justify-between gap-3 rounded-xl bg-[var(--surface-muted)] p-4 text-sm"><div><span className="font-bold text-[var(--brand)]">Response target</span><span className="ml-2 text-slate-600">{new Date(item.target_response_at).toLocaleString()}</span></div>{item.overdue && <span className="rounded-full bg-red-100 px-3 py-1 text-xs font-black text-red-800">Operations follow-up due</span>}<p className="w-full text-xs leading-5 text-slate-500">Our team usually checks availability within this displayed window. It is an operational target, not a guarantee.</p></div>; }

function OperationalNotices({ item }: { item: SafariRequest }) { return <section className="mt-5" aria-labelledby={`notices-${item.id}`}><h3 id={`notices-${item.id}`} className="text-sm font-black text-[var(--brand)]">Important information</h3><div className="mt-3 space-y-2">{item.safari.operational_notices.map((notice) => <article key={notice.id} className={`rounded-xl border p-4 ${notice.severity === "RESTRICTION" ? "border-red-200 bg-red-50" : notice.severity === "WARNING" ? "border-amber-200 bg-amber-50" : "border-blue-100 bg-blue-50"}`}><p className="font-bold text-[var(--ink)]">{notice.title}</p><p className="mt-1 whitespace-pre-wrap text-sm leading-6 text-slate-700">{notice.body}</p></article>)}</div></section>; }

function bookingSelection(item: SafariRequest) { const selected = item.alternatives.find((value) => value.id === item.selected_alternative_id); return { date: selected?.safari_date || item.preferred_date, shift: selected?.shift || item.preferred_shift, category: selected?.booking_category || item.preferred_booking_category, vehicle: selected?.vehicle_option || item.preferred_vehicle_option, zone: selected?.zone, gate: selected?.gate }; }

function AvailabilityFound({ item }: { item: SafariRequest }) { const selection = bookingSelection(item); return <section className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-5"><p className="text-xs font-black uppercase tracking-[.14em] text-emerald-700">Availability found</p><h3 className="mt-2 text-lg font-black text-emerald-950">Continue with traveller details</h3><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><Data label="Date" value={formatDate(selection.date)} /><Data label="Shift" value={selection.shift} /><Data label="Booking category" value={selection.category ? pretty(selection.category) : undefined} /><Data label="Vehicle" value={selection.vehicle ? pretty(selection.vehicle) : undefined} /><Data label="Zone" value={selection.zone} /><Data label="Gate" value={selection.gate} /></dl></section>; }

function Alternatives({ item, busy, onSelect }: { item: SafariRequest; busy: boolean; onSelect: (id: number) => void }) {
  if (!item.alternatives.length) return <p className="mt-5 rounded-xl bg-[var(--surface-muted)] p-4 text-sm text-slate-600">No alternative option was offered for this request.</p>;
  return <section className="mt-6" aria-labelledby={`alternatives-${item.id}`}><h3 id={`alternatives-${item.id}`} className="text-lg font-black text-[var(--brand)]">Alternatives offered by Maharashtra Tourist Places</h3><div className="mt-3 grid gap-3">{item.alternatives.map((alternative) => <div key={alternative.id} className="rounded-xl border border-[var(--line)] p-4 sm:flex sm:items-center sm:justify-between sm:gap-5"><div className="text-sm"><p className="font-black">{formatDate(alternative.safari_date)}{alternative.shift ? ` · ${alternative.shift}` : ""}</p>{(alternative.zone || alternative.gate || alternative.booking_category || alternative.vehicle_option) && <p className="mt-1 text-slate-600">{[alternative.zone, alternative.gate, alternative.booking_category && pretty(alternative.booking_category), alternative.vehicle_option && pretty(alternative.vehicle_option)].filter(Boolean).join(" · ")}</p>}{alternative.note && <p className="mt-2 leading-6 text-slate-500">{alternative.note}</p>}</div><button type="button" disabled={busy} onClick={() => onSelect(alternative.id)} className="primary-button mt-4 shrink-0 sm:mt-0">Select alternative</button></div>)}</div></section>;
}

function TravellerRequirements({ item, busy, setBusy, onUpdate, setError }: { item: SafariRequest; busy: boolean; setBusy: (value: boolean) => void; onUpdate: (item: SafariRequest, message?: string) => void; setError: (value: string) => void }) {
  const fields = item.safari.traveller_requirements.fields ?? []; const documents = item.safari.traveller_requirements.documents ?? [];
  const [details, setDetails] = useState<Array<Record<string, string>>>(() => Array.from({ length: item.visitor_count }, () => ({})));
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); try { onUpdate(await safariService.travellers(item.id, details.map((value) => ({ details: value }))), "Traveller details saved securely. Upload any configured documents, then submit."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Traveller details could not be saved."); } finally { setBusy(false); } }
  async function upload(travellerId: number, type: string, file?: File) { if (!file) return; if (file.size > PRIVATE_DOCUMENT_MAX_BYTES) { setError("The private document must be 10 MB or smaller."); return; } setBusy(true); setError(""); try { await safariService.uploadTravellerDocument(item.id, travellerId, type, file); onUpdate(await safariService.getRequest(item.id), "Document uploaded securely."); } catch (cause) { setError(cause instanceof Error ? cause.message : "The document could not be uploaded."); } finally { setBusy(false); } }
  async function submit() { setBusy(true); setError(""); try { onUpdate(await safariService.submitTravellers(item.id), "Traveller requirements submitted. Maharashtra Tourist Places will show payment only after authoritative pricing is ready."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Traveller requirements could not be submitted."); } finally { setBusy(false); } }
  if (!item.travellers.length) return <form onSubmit={save} className="mt-6 rounded-xl border border-[var(--line)] bg-[var(--surface-muted)] p-5"><h3 className="text-lg font-black text-[var(--brand)]">Traveller details</h3><p className="mt-2 text-xs leading-5 text-slate-500">Only fields configured for this safari are requested. The data is encrypted by Maharashtra Tourist Places and is not displayed again on this page.</p><div className="mt-5 space-y-5">{Array.from({ length: item.visitor_count }, (_, index) => <fieldset key={index} className="rounded-xl border border-[var(--line)] bg-white p-4"><legend className="px-2 text-sm font-black text-[var(--brand)]">Traveller {index + 1}</legend><div className="grid gap-4 sm:grid-cols-2">{fields.map((field) => <label key={field.key} className="field-label block" htmlFor={`${item.id}-${index}-${field.key}`}>{field.label || pretty(field.key)}{field.required ? " *" : ""}<input id={`${item.id}-${index}-${field.key}`} required={field.required} type={inputType(field.type)} autoComplete="off" value={details[index]?.[field.key] ?? ""} onChange={(event) => setDetails((current) => current.map((value, position) => position === index ? { ...value, [field.key]: event.target.value } : value))} className="field-input mt-2" /></label>)}</div>{!fields.length && <p className="text-sm text-slate-500">No text fields are configured. Save each traveller slot to continue.</p>}</fieldset>)}</div><button disabled={busy} className="primary-button mt-5">{busy ? "Saving securely…" : "Save traveller details"}</button></form>;
  const ready = item.travellers.every((traveller) => documents.filter((doc) => doc.required).every((doc) => traveller.documents.some((uploaded) => uploaded.document_type === doc.type)));
  return <section className="mt-6 rounded-xl border border-[var(--line)] bg-[var(--surface-muted)] p-5"><h3 className="text-lg font-black text-[var(--brand)]">Secure traveller documents</h3><p className="mt-2 text-xs leading-5 text-slate-500">Details are saved. Upload only the documents configured below; files stay behind authenticated access.</p><div className="mt-5 space-y-4">{item.travellers.map((traveller) => <TravellerDocuments key={traveller.id} traveller={traveller} requirements={documents} busy={busy} onUpload={(type, file) => void upload(traveller.id, type, file)} />)}</div>{!documents.length && <p className="mt-4 text-sm text-slate-600">No documents are configured for this safari.</p>}<button type="button" disabled={busy || !ready} onClick={() => void submit()} className="primary-button mt-5">{busy ? "Submitting…" : "Submit traveller requirements"}</button>{!ready && <p className="mt-2 text-xs font-semibold text-amber-700">Upload each required document before submitting.</p>}</section>;
}

function TravellerDocuments({ traveller, requirements, busy, onUpload }: { traveller: SafariTraveller; requirements: NonNullable<SafariRequest["safari"]["traveller_requirements"]["documents"]>; busy: boolean; onUpload: (type: string, file?: File) => void }) { return <fieldset className="rounded-xl border border-[var(--line)] bg-white p-4"><legend className="px-2 text-sm font-black text-[var(--brand)]">Traveller {traveller.position}</legend><div className="space-y-3">{requirements.map((document) => { const uploaded = traveller.documents.some((value) => value.document_type === document.type); return <div key={document.type}><label className="field-label block" htmlFor={`document-${traveller.id}-${document.type}`}>{document.label || pretty(document.type)}{document.required ? " *" : ""}<input id={`document-${traveller.id}-${document.type}`} type="file" disabled={busy || uploaded} accept="application/pdf,image/jpeg,image/png" onChange={(event) => onUpload(document.type, event.target.files?.[0])} className="mt-2 block w-full text-sm text-slate-600 file:mr-3 file:rounded-lg file:border-0 file:bg-[var(--accent-soft)] file:px-4 file:py-2 file:font-bold file:text-[var(--accent-strong)]" /></label><p className={`mt-1 text-xs font-semibold ${uploaded ? "text-emerald-700" : "text-slate-500"}`}>{uploaded ? "Uploaded securely" : "PDF, JPEG or PNG, maximum 10 MB"}</p></div>; })}</div></fieldset>; }

function PriceReview({ item }: { item: SafariRequest }) {
  if (!item.payable_amount || !item.currency) return <div className="mt-5 rounded-xl border border-[var(--line)] bg-[var(--surface-muted)] p-5"><p className="font-black text-[var(--brand)]">Authoritative price pending</p><p className="mt-2 text-sm leading-6 text-slate-600">Payment is unavailable until Maharashtra Tourist Places operations confirms the final amount.</p></div>;
  const amount = item.payable_amount; const currency = item.currency;
  const selection = bookingSelection(item);
  const entries = Object.entries(item.price_breakdown ?? {}).filter(([, value]) => typeof value === "string" || typeof value === "number");
  return <section className="mt-5 rounded-xl border border-[var(--line)] bg-[var(--surface-muted)] p-5" aria-labelledby={`price-${item.id}`}><h3 id={`price-${item.id}`} className="font-black text-[var(--brand)]">Booking review</h3><dl className="mt-4 grid gap-3 border-b border-[var(--line)] pb-4 text-sm sm:grid-cols-2"><Data label="Safari" value={item.safari.name} /><Data label="Date" value={formatDate(selection.date)} /><Data label="Shift" value={selection.shift} /><Data label="Booking category" value={selection.category ? pretty(selection.category) : undefined} /><Data label="Vehicle" value={selection.vehicle ? pretty(selection.vehicle) : undefined} /><Data label="Zone / gate" value={[selection.zone, selection.gate].filter(Boolean).join(" · ") || undefined} /><Data label="Visitors" value={String(item.visitor_count)} /><Data label="Traveller details" value={`${item.travellers.length} of ${item.visitor_count} saved`} /></dl><h4 className="mt-4 text-sm font-black text-[var(--brand)]">Authoritative price</h4>{entries.length > 0 && <dl className="mt-3 space-y-2 border-b border-[var(--line)] pb-4 text-sm">{entries.map(([label, value]) => <div key={label} className="flex justify-between gap-4"><dt className="text-slate-600">{pretty(label)}</dt><dd className="font-bold">{typeof value === "number" || !Number.isNaN(Number(value)) ? formatMoney(String(value), currency) : String(value)}</dd></div>)}</dl>}<div className="mt-4 flex items-end justify-between gap-4"><span className="font-black">Total payable</span><span className="text-2xl font-black text-[var(--brand)]">{formatMoney(amount, currency)}</span></div><p className="mt-3 text-xs leading-5 text-slate-500">This amount and breakdown are supplied by Maharashtra Tourist Places operations. The frontend does not calculate or alter them.</p></section>;
}

function PaymentPanel({ item, busy, onCreate }: { item: SafariRequest; busy: boolean; onCreate: () => void }) {
  if (item.payment_status === "PENDING") return <div className="mt-4 rounded-xl border border-amber-100 bg-amber-50 p-4"><p className="font-bold text-amber-900">Payment confirmation pending</p><p className="mt-1 text-sm leading-6 text-amber-800">A payment session already exists. Maharashtra Tourist Places waits for a signed provider callback; do not create or report payment manually.</p></div>;
  if (item.payment_status === "PAID") return <div className="mt-4 rounded-xl border border-blue-100 bg-blue-50 p-4"><p className="font-bold text-blue-900">Payment received; status reconciliation in progress</p><p className="mt-1 text-sm text-blue-800">Do not pay again. Maharashtra Tourist Places operations will reconcile the booking state.</p></div>;
  return <button type="button" disabled={busy || !item.payable_amount} onClick={onCreate} className="primary-button mt-4">{busy ? "Creating secure payment…" : item.payment_status === "FAILED" ? "Retry payment" : "Continue to payment"}</button>;
}

function Confirmation({ item, busy, hotelHref, onDownload }: { item: SafariRequest; busy: boolean; hotelHref?: string; onDownload: (id: number, name: string) => void }) { return <section className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-5"><p className="text-xs font-black uppercase tracking-[.14em] text-emerald-700">Safari confirmation</p><h3 className="mt-2 text-xl font-black text-emerald-950">{item.external_booking_reference || item.request_reference}</h3><dl className="mt-4 grid gap-4 text-sm sm:grid-cols-2"><Data label="Date" value={item.confirmed_date ? formatDate(item.confirmed_date) : undefined} /><Data label="Shift" value={item.confirmed_shift} /><Data label="Zone" value={item.confirmed_zone} /><Data label="Gate" value={item.confirmed_gate} /><Data label="Booking category" value={item.confirmed_booking_category ? pretty(item.confirmed_booking_category) : undefined} /><Data label="Vehicle" value={item.confirmed_vehicle_option ? pretty(item.confirmed_vehicle_option) : undefined} /><Data label="Official booking contact" value={item.official_booking_contact_masked} /><Data label="Travellers" value={String(item.visitor_count)} /><Data label="Payment" value={pretty(item.payment_status)} /><Data label="Operator confirmed" value={item.operator_confirmed_at ? new Date(item.operator_confirmed_at).toLocaleString() : undefined} /></dl>{item.reporting_instructions && <div className="mt-5 border-t border-emerald-200 pt-4"><p className="font-black text-emerald-950">Reporting information</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-emerald-900">{item.reporting_instructions}</p></div>}{item.confirmation_documents.length > 0 && <div className="mt-5 border-t border-emerald-200 pt-4"><p className="font-black text-emerald-950">Secure documents</p><div className="mt-3 flex flex-wrap gap-2">{item.confirmation_documents.map((document) => <button type="button" key={document.id} disabled={busy} onClick={() => onDownload(document.id, document.original_name)} className="secondary-button !min-h-10">Download {pretty(document.document_type)}</button>)}</div><p className="mt-2 text-xs text-emerald-800">Downloads require your authenticated customer session.</p></div>}{hotelHref && <Link href={hotelHref} className="secondary-button mt-5">Find stays nearby</Link>}</section>; }

function FailurePanel({ item }: { item: SafariRequest }) { return <div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-5"><p className="font-black text-red-900">External booking failed</p>{item.failure_reason && <p className="mt-2 text-sm leading-6 text-red-800">{item.failure_reason}</p>}<dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><Data label="Refund" value={item.refund_status ? pretty(item.refund_status) : "Pending review"} /><Data label="Reconciliation" value={item.payment_reconciliation_status ? pretty(item.payment_reconciliation_status) : "In progress"} /></dl><p className="mt-3 text-xs leading-5 text-red-700">The booking remains failed even if a provider refund is delayed. Maharashtra Tourist Places tracks the payment through reconciliation.</p></div>; }
function Data({ label, value }: { label: string; value?: string }) { if (!value) return null; return <div><dt className="text-slate-500">{label}</dt><dd className="mt-1 font-black text-[var(--ink)]">{value}</dd></div>; }
function pretty(value: string) { return value.replaceAll("_", " ").toLowerCase().replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function inputType(value?: string) { return value === "date" ? "date" : value === "number" ? "number" : value === "email" ? "email" : "text"; }
function formatDate(value: string) { return new Date(`${value}T00:00:00`).toLocaleDateString(undefined, { day: "numeric", month: "short", year: "numeric" }); }
function formatMoney(value: string, currency: string) { const amount = Number(value); return Number.isFinite(amount) ? new Intl.NumberFormat(undefined, { style: "currency", currency }).format(amount) : `${currency} ${value}`; }
