"""create hotel management foundation

Revision ID: fa02e98ce338
Revises: abdfda42cd68
Create Date: 2026-08-16 23:52:43.002016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa02e98ce338'
down_revision: Union[str, Sequence[str], None] = 'abdfda42cd68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_amenities_category'), 'amenities', ['category'], unique=False)
    op.create_index(op.f('ix_amenities_slug'), 'amenities', ['slug'], unique=True)
    op.create_table('hotels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('property_type', sa.Enum('HOTEL', 'RESORT', 'VILLA', 'APARTMENT', 'HOSTEL', 'HOMESTAY', name='property_type'), nullable=False),
    sa.Column('star_rating', sa.Numeric(precision=2, scale=1), server_default='0.0', nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'INACTIVE', 'SUSPENDED', name='hotel_status'), server_default='DRAFT', nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=16), nullable=True),
    sa.Column('check_in_time', sa.Time(), nullable=False),
    sa.Column('check_out_time', sa.Time(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('latitude IS NULL OR (latitude >= -90 AND latitude <= 90)', name='ck_hotels_latitude'),
    sa.CheckConstraint('longitude IS NULL OR (longitude >= -180 AND longitude <= 180)', name='ck_hotels_longitude'),
    sa.CheckConstraint('star_rating >= 0 AND star_rating <= 5', name='ck_hotels_star_rating'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotels_city'), 'hotels', ['city'], unique=False)
    op.create_index(op.f('ix_hotels_country'), 'hotels', ['country'], unique=False)
    op.create_index('ix_hotels_location', 'hotels', ['country', 'state', 'city'], unique=False)
    op.create_index(op.f('ix_hotels_slug'), 'hotels', ['slug'], unique=True)
    op.create_index(op.f('ix_hotels_state'), 'hotels', ['state'], unique=False)
    op.create_index(op.f('ix_hotels_status'), 'hotels', ['status'], unique=False)
    op.create_table('hotel_amenities',
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('amenity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenities.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hotel_id', 'amenity_id')
    )
    op.create_table('hotel_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=2048), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('is_cover', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('display_order >= 0', name='ck_hotel_images_display_order'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hotel_images_hotel_id'), 'hotel_images', ['hotel_id'], unique=False)
    op.create_table('hotel_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('cancellation_policy', sa.Text(), nullable=True),
    sa.Column('children_policy', sa.Text(), nullable=True),
    sa.Column('pet_policy', sa.Text(), nullable=True),
    sa.Column('smoking_policy', sa.Text(), nullable=True),
    sa.Column('extra_bed_policy', sa.Text(), nullable=True),
    sa.Column('additional_rules', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_id')
    )
    op.create_table('room_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('max_adults', sa.Integer(), nullable=False),
    sa.Column('max_children', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_guests', sa.Integer(), nullable=False),
    sa.Column('bed_type', sa.String(length=100), nullable=False),
    sa.Column('bed_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('room_size_sqm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('total_rooms', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('base_price >= 0', name='ck_room_types_base_price'),
    sa.CheckConstraint('bed_count >= 1', name='ck_room_types_bed_count'),
    sa.CheckConstraint('max_adults >= 1', name='ck_room_types_max_adults'),
    sa.CheckConstraint('max_children >= 0', name='ck_room_types_max_children'),
    sa.CheckConstraint('max_guests >= 1', name='ck_room_types_max_guests'),
    sa.CheckConstraint('room_size_sqm IS NULL OR room_size_sqm > 0', name='ck_room_types_size'),
    sa.CheckConstraint('total_rooms >= 0', name='ck_room_types_total_rooms'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hotel_id', 'name', name='uq_room_types_hotel_name')
    )
    op.create_index(op.f('ix_room_types_hotel_id'), 'room_types', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_room_types_is_active'), 'room_types', ['is_active'], unique=False)
    op.create_table('room_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=2048), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('is_cover', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('display_order >= 0', name='ck_room_images_display_order'),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_images_room_type_id'), 'room_images', ['room_type_id'], unique=False)
    op.create_table('room_inventory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_type_id', sa.Integer(), nullable=False),
    sa.Column('inventory_date', sa.Date(), nullable=False),
    sa.Column('total_inventory', sa.Integer(), nullable=False),
    sa.Column('available_inventory', sa.Integer(), nullable=False),
    sa.Column('blocked_inventory', sa.Integer(), server_default='0', nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_closed', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('available_inventory + blocked_inventory <= total_inventory', name='ck_room_inventory_allocations'),
    sa.CheckConstraint('available_inventory <= total_inventory', name='ck_room_inventory_available_total'),
    sa.CheckConstraint('available_inventory >= 0', name='ck_room_inventory_available'),
    sa.CheckConstraint('blocked_inventory <= total_inventory', name='ck_room_inventory_blocked_total'),
    sa.CheckConstraint('blocked_inventory >= 0', name='ck_room_inventory_blocked'),
    sa.CheckConstraint('price >= 0', name='ck_room_inventory_price'),
    sa.CheckConstraint('total_inventory >= 0', name='ck_room_inventory_total'),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_type_id', 'inventory_date', name='uq_room_inventory_room_date')
    )
    op.create_index('ix_room_inventory_room_date', 'room_inventory', ['room_type_id', 'inventory_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_room_inventory_room_date', table_name='room_inventory')
    op.drop_table('room_inventory')
    op.drop_index(op.f('ix_room_images_room_type_id'), table_name='room_images')
    op.drop_table('room_images')
    op.drop_index(op.f('ix_room_types_is_active'), table_name='room_types')
    op.drop_index(op.f('ix_room_types_hotel_id'), table_name='room_types')
    op.drop_table('room_types')
    op.drop_table('hotel_policies')
    op.drop_index(op.f('ix_hotel_images_hotel_id'), table_name='hotel_images')
    op.drop_table('hotel_images')
    op.drop_table('hotel_amenities')
    op.drop_index(op.f('ix_hotels_status'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_state'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_slug'), table_name='hotels')
    op.drop_index('ix_hotels_location', table_name='hotels')
    op.drop_index(op.f('ix_hotels_country'), table_name='hotels')
    op.drop_index(op.f('ix_hotels_city'), table_name='hotels')
    op.drop_table('hotels')
    op.drop_index(op.f('ix_amenities_slug'), table_name='amenities')
    op.drop_index(op.f('ix_amenities_category'), table_name='amenities')
    op.drop_table('amenities')
    # ### end Alembic commands ###
